Repository raft-tech/TANF-app, pull requests merged in 2021-06, with the labels that each got.

#986 Hotfix: Resolve breaking change in PyJWT upgrade
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/test/test_auth.py
Labels: Dev Top Priority, Ready to Merge, backend, dev

#894 Issue 374: Capture UUID during login.gov setup
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/authentication.py
  tdrs-backend/tdpservice/users/migrations/0013_user_sub.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/test/factories.py
  tdrs-backend/tdpservice/users/test/test_auth.py
Labels: Ready to Merge, backend, dev

#916 Issue 858: Upload functionality improvements
  tdrs-frontend/src/components/EditProfile/EditProfile.jsx
  tdrs-frontend/src/components/EditProfile/EditProfile.test.js
  tdrs-frontend/src/components/Reports/Reports.jsx
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/UploadReport/UploadReport.jsx
  tdrs-frontend/src/reducers/reports.js
Labels: Deploy with CircleCI, Ready to Merge, a11y, dev, frontend

#664 Issue 643: Endpoint for retrieving a list of years reports are available
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/reports/models.py
  tdrs-backend/tdpservice/reports/test/test_api.py
  tdrs-backend/tdpservice/reports/urls.py
  tdrs-backend/tdpservice/reports/views.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/users/permissions.py
  tdrs-backend/tdpservice/users/test/factories.py
  tdrs-backend/tdpservice/users/test/test_auth.py
Labels: Ready to Merge, backend, dev

#866 Issue 865: Add 404 routes to nginx config file
  scripts/deploy-frontend.sh
  tdrs-frontend/Dockerfile.dev
  tdrs-frontend/nginx/buildpack.nginx.conf
  tdrs-frontend/nginx/locations.conf
  tdrs-frontend/nginx/nginx.conf
  tdrs-frontend/src/components/NoMatch/NoMatch.jsx
  tdrs-frontend/src/components/NoMatch/index.jsx
  tdrs-frontend/src/components/Reports/Reports.jsx
  tdrs-frontend/src/components/Routes/Routes.js
  tdrs-frontend/src/components/Routes/Routes.test.js
Labels: Deploy with CircleCI, Ready to Merge, dev, frontend

#985 Secret key prevention doc
  docs/How-We-Work/Secrey-Key-Mgmt.md
Labels: Ready to Merge, documentation

#1006 Create sprint-21-summary.md
  docs/Sprint-Review/sprint-21-summary.md
Labels: Deploy with CircleCI, Ready to Merge, documentation

#1005 Create sprint-22-summary.md
  docs/Sprint-Review/sprint-22-summary.md
Labels: Ready to Merge, documentation

#991 Update Roadmap-and-Backlog.md
  docs/Product-Strategy/Roadmap-and-Backlog.md
Labels: Ready to Merge, documentation

#1033 Update Team-Composition.md
  docs/How-We-Work/Team-Composition.md
Labels: Ready to Merge, documentation

#1034 Update 009-git-workflow.md
  docs/Architecture Decision Record/009-git-workflow.md
Labels: Ready to Merge, documentation

#1009 Removed Unused Dockerfiles
  .circleci/config.yml
  tdrs-backend/Dockerfile
  tdrs-backend/README.md
  tdrs-backend/docker-compose.yml
  tdrs-backend/docker/Dockerfile.dev
  tdrs-backend/docker/Dockerfile.local
  tdrs-frontend/Dockerfile
  tdrs-frontend/Dockerfile.local
  tdrs-frontend/Dockerfile.staging
  tdrs-frontend/README.md
  tdrs-frontend/docker-compose.local.yml
  tdrs-frontend/docker-compose.yml
Labels: DX, Ready to Merge, ci/cd, devops

#1022 Update 009-git-workflow.md
  docs/Architecture Decision Record/009-git-workflow.md
Labels: documentation, raft review

#1041 Devops/872/update pa11y config
  .circleci/config.yml
  tdrs-frontend/.pa11yci.json
Labels: Ready to Merge, a11y, dev, devops

#930 Issue 829: Communicate to user if they are inactive
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/migrations/0014_add_user_deactivated.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/serializers.py
  tdrs-backend/tdpservice/users/test/factories.py
  tdrs-backend/tdpservice/users/test/test_auth.py
  tdrs-backend/tdpservice/users/test/test_auth_check.py
  tdrs-frontend/.eslintrc.json
  tdrs-frontend/package.json
  tdrs-frontend/src/actions/auth.js
  tdrs-frontend/src/actions/auth.test.js
  tdrs-frontend/src/components/EditProfile/EditProfile.test.js
  tdrs-frontend/src/components/SplashPage/SplashPage.jsx
  tdrs-frontend/src/components/SplashPage/SplashPage.test.js
  tdrs-frontend/src/reducers/auth.js
  tdrs-frontend/src/reducers/auth.test.js
Labels: Dev Top Priority, Ready to Merge, backend, dev, frontend

#941 Add zap configs to ignore false positives
  .circleci/config.yml
  tdrs-backend/reports/.gitignore
  tdrs-backend/reports/zap.conf
  tdrs-backend/zap-scanner.sh
  tdrs-frontend/reports/.gitignore
  tdrs-frontend/reports/zap.conf
  tdrs-frontend/zap-scanner.sh
Labels: Ready to Merge, ci/cd, devops

#861 Issue 818 (PR #2): Add endpoint to scan and upload a Data File to S3
  .circleci/config.yml
  scripts/localstack-setup.sh
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/README.md
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/reports/migrations/0006_reportfile_file.py
  tdrs-backend/tdpservice/reports/models.py
  tdrs-backend/tdpservice/reports/serializers.py
  tdrs-backend/tdpservice/reports/test/conftest.py
  tdrs-backend/tdpservice/reports/test/factories.py
  tdrs-backend/tdpservice/reports/test/test_api.py
  tdrs-backend/tdpservice/reports/test/test_serializers.py
  tdrs-backend/tdpservice/reports/validators.py
  tdrs-backend/tdpservice/reports/views.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/settings/development.py
  tdrs-backend/tdpservice/settings/local.py
  tdrs-backend/tdpservice/settings/production.py
  tdrs-backend/tdpservice/settings/staging.py
  tdrs-backend/tdpservice/users/permissions.py
  tdrs-backend/wait_for_services.sh
  tdrs-backend/zap-scanner.sh
Labels: Deploy with CircleCI, Dev Top Priority, Ready to Merge, backend, dev
