Repository raft-tech/TANF-app, pull requests merged in 2021-03, with the labels that each got.

#715 Update Team-Composition.md
  docs/How-We-Work/Team-Composition.md
Labels: QASP Review, documentation

#713 Update definition-of-done.md
  docs/How-We-Work/team-charter/definition-of-done.md
Labels: QASP Review, documentation

#727 Create sprint-15-summary.md
  docs/Sprint-Review/sprint-15-summary.md
Labels: QASP Review, documentation

#736 Move Sprint 3 Summary.md to Sprint-Review subfolder
  docs/Sprint-Review/Sprint 3 Summary.md
Labels: Ready to Merge

#581 [issues/519/backend] Allow creating super users through admin panel
  docs/Architecture Decision Record/010-assign-superuser.md
  docs/Technical-Documentation/images/admin_users.png
  docs/Technical-Documentation/images/user_edit.png
  docs/Technical-Documentation/user_role_management.md
  tdrs-backend/.env.example
  tdrs-backend/README.md
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/test/test_admin.py
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/migrations/0012_add_initial_super_user.py
Labels: Dev Top Priority, QASP Review, backend, dev

#725 Update boundary diagram
  docs/Security-Compliance/diagram.drawio
  docs/Security-Compliance/diagram.png
  docs/Security-Compliance/diagram.vsdx
Labels: Ready to Merge, documentation

#675 Documentation/access controls ac 2(3)
  docs/Security-Compliance/Security-Controls/ac-2-3/index.md
  docs/Security-Compliance/Security-Controls/ac-2-3/user_profile_last_login.png
Labels: Ready to Merge, security controls

#677 Create ac-2(10).md
  docs/Security-Compliance/Security-Controls/ac-2-10/index.md
Labels: Ready to Merge, security controls

#676 Documentation/access control ac 2(7)
  docs/Security-Compliance/Security-Controls/ac-2-7/index.md
Labels: Ready to Merge, security controls

#679 Create ac-2(9).md
  docs/Security-Compliance/Security-Controls/ac-2-9/index.md
Labels: Ready to Merge, security controls

#740 Update our-workflow.md
  docs/How-We-Work/team-charter/our-workflow.md
Labels: QASP Review, documentation

#718 Add initial doc for buildpack ADR
  docs/Architecture Decision Record/011-buildpacks.md
Labels: ADR, Ready to Merge, devops, documentation

#686 [Snyk] Security upgrade django from 3.1.4 to 3.1.7
  tdrs-backend/requirements.txt
Labels: Ready to Merge, snyk upgrades

#719 [Snyk] Upgrade react-scripts from 4.0.0 to 4.0.3
  tdrs-frontend/package.json
Labels: QASP Review, dev, frontend, snyk upgrades

#642 [Snyk] Upgrade: @fortawesome/fontawesome-svg-core, @fortawesome/free-solid-svg-icons
  tdrs-frontend/package.json
  tdrs-frontend/yarn.lock
Labels: QASP Review, snyk upgrades

#593 Automatic Generation of OpenAPI documentation
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/requirements.txt
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/urls.py
Labels: Dev Top Priority, QASP Review, backend, dev, documentation

#567 [Snyk] Upgrade eslint from 7.16.0 to 7.17.0
  tdrs-frontend/package.json
Labels: Ready to Merge, snyk upgrades

#739 SC-04 - Information in Shared Resources
  docs/Security-Compliance/Security-Controls/sc-4/index.md
Labels: OCIO Review, documentation, security controls

#745 Security Controls: SC-08
  docs/Security-Compliance/Security-Controls/sc-8/index.md
Labels: OCIO Review, documentation, security controls

#742 Add GitHub Action to trigger deploys on PR label assignment [720]
  .circleci/config.yml
  .github/workflows/deploy-on-label.yml
  README.md
Labels: DX, Deploy with CircleCI, Dev Top Priority, Ready to Merge, dev, devops

#758 Update Roadmap-and-Backlog.md
  docs/Product-Strategy/Roadmap-and-Backlog.md
Labels: Ready to Merge, documentation

#766 Create sprint-16-summary.md
  docs/Sprint-Review/sprint-16-summary.md
Labels: Ready to Merge, documentation

#746 Update sprint-schedule.md
  docs/How-We-Work/team-charter/sprint-schedule.md
Labels: Ready to Merge, documentation

#775 Create bug-template.md
  .github/ISSUE_TEMPLATE/bug-template.md
Labels: GitHub Templates, Ready to Merge, documentation

#780 update bug report
  .github/ISSUE_TEMPLATE/bug-template.md
Labels: DX, Ready to Merge, dev

#741 Issue 691: As a developer, I would like the app to hot reload when running locally
  README.md
  tdrs-frontend/Dockerfile.local
  tdrs-frontend/README.md
  tdrs-frontend/docker-compose.local.yml
  tdrs-frontend/docker-compose.yml
Labels: DX, Dev Top Priority, Ready to Merge, dev

#765 Issue 669: Research Synthesis for Round 4
  docs/User-Research/Winter 2021, Round 4 Synthesis.md
Labels: Ready to Merge, Research & Design

#784 Update Project-Glossary.md
  docs/Background/Project-Glossary.md
Labels: Ready to Merge, documentation

#650 Issue 639: As an OFA Admin, I need to be able to access the admin functions in TDP
  .gitignore
  tdrs-frontend/.env
  tdrs-frontend/.env.development
  tdrs-frontend/.env.test
  tdrs-frontend/Dockerfile.dev
  tdrs-frontend/Dockerfile.staging
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
  tdrs-frontend/src/components/NavItem/NavItem.jsx
Labels: Dev Top Priority, Ready to Merge, dev, frontend

#791 792: Failing deploys to development environment
  tdrs-frontend/manifest.yml
Labels: Deploy with CircleCI, Dev Top Priority, QASP Review, devops

#705 Issue 429: Add component to input single file
  tdrs-frontend/src/actions/reports.js
  tdrs-frontend/src/actions/reports.test.js
  tdrs-frontend/src/assets/FileUpload.scss
  tdrs-frontend/src/assets/uswds/_uswds-theme-utilities.scss
  tdrs-frontend/src/components/ComboBox/ComboBox.jsx
  tdrs-frontend/src/components/FileUpload/FileUpload.jsx
  tdrs-frontend/src/components/FileUpload/index.js
  tdrs-frontend/src/components/NavItem/NavItem.jsx
  tdrs-frontend/src/components/Reports/Reports.jsx
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/Routes/Routes.test.js
  tdrs-frontend/src/components/UploadReport/UploadReport.jsx
  tdrs-frontend/src/components/UploadReport/UploadReport.test.js
  tdrs-frontend/src/components/UploadReport/index.js
  tdrs-frontend/src/index.scss
  tdrs-frontend/src/reducers/reports.js
  tdrs-frontend/src/reducers/reports.test.js
Labels: dev, frontend

#805 Issue 793: As a dev, I want to use a simulated AWS environment during tests and local dev
  tdrs-backend/README.md
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/clients.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/settings/test.py
  tdrs-backend/tdpservice/test/test_clients.py
Labels: Dev Top Priority, QASP Review, dev, devops

#757 Issue 429-2: Change Reports to Data Files
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
  tdrs-frontend/src/components/Routes/Routes.js
  tdrs-frontend/src/components/UploadReport/UploadReport.jsx
Labels: Deploy with CircleCI, QASP Review, dev, frontend
