Repository raft-tech/TANF-app, pull requests merged in 2021-12, with the labels that each got.

#1472 Update our-team-and-values.md
  docs/How-We-Work/team-charter/our-team-and-values.md
Labels: documentation, Ready to Merge

#1471 Update sprint-schedule.md
  docs/How-We-Work/team-charter/sprint-schedule.md
Labels: documentation, Ready to Merge

#1470 Update team-meetings.md
  docs/How-We-Work/team-charter/team-meetings.md
Labels: documentation, Ready to Merge

#1474 Issue 1427: Remove usage of Cypress in the project
  .circleci/config.yml
  .github/dependabot.yml
  README.md
  docs/Technical-Documentation/circle-ci.md
  docs/Technical-Documentation/unit-tests.md
  tdrs-frontend/.eslintrc.json
  tdrs-frontend/README.md
  tdrs-frontend/cypress.json
  tdrs-frontend/cypress/integration/login.spec.js
  tdrs-frontend/cypress/integration/welcome_page_greeting.spec.js
  tdrs-frontend/cypress/plugins/index.js
  tdrs-frontend/package.json
  tdrs-frontend/src/mirage.js
  tdrs-frontend/yarn.lock
Labels: frontend, Ready to Merge, ci/cd

#1473 Delete team-charter.md
  docs/How-We-Work/team-charter/team-charter.md
Labels: documentation, Ready to Merge

#1430 Issue 1165: Resolve Cache Control header error by ZAP
  tdrs-backend/tdpservice/middleware.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-frontend/nginx/buildpack.nginx.conf
Labels: frontend, backend, security, Ready to Merge

#1465 git-secrets-check PATH update
  .github/pull_request_template.md
  scripts/git-secrets-check.sh
Labels: dev, devops, Ready to Merge, DX

#1457 Logging level dictated by env var
  tdrs-backend/.env.example
  tdrs-backend/docker-compose.yml
  tdrs-backend/gunicorn_start.sh
  tdrs-backend/tdpservice/security/clients.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/stts/management/commands/populate_stts.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/api/utils.py
  tdrs-backend/tdpservice/users/serializers.py
Labels: backend, dev, Ready to Merge, Deploy with CircleCI-qasp

#1467 fix(1451): remove sidenav menu for logged out users
  tdrs-frontend/src/components/Header/Header.jsx
Labels: frontend, dev, Ready to Merge

#1475 Dependabot security alerts
  tdrs-frontend/package.json
  tdrs-frontend/yarn.lock
Labels: dependencies, frontend, security, dev, Ready to Merge

#1486 Update 018-developer-tabletops.md
  docs/Architecture Decision Record/018-developer-tabletops.md
Labels: documentation, Ready to Merge

#1464 build(1405): update django to 3.2.9
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: dependencies, backend, dev, Ready to Merge, Deploy with CircleCI-qasp

#1458 Create sprint-34-summary.md
  docs/Sprint-Review/sprint-34-summary.md
Labels: documentation, Ready to Merge

#1485 Create sprint-35-summary.md
  docs/Sprint-Review/sprint-35-summary.md
Labels: documentation, Ready to Merge

#1501 Update communication-tools.md
  docs/How-We-Work/team-charter/communication-tools.md
Labels: Ready to Merge

#1490 build(1143): Update django-admin-508 with default fonts to address S3 CORS issues
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: dependencies, dev, DAC, Ready to Merge

#1503 update django to version 3.2.10
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: dependencies, backend, security, dev, Ready to Merge
