Repository raft-tech/TANF-app, pull requests merged in 2021-09, with the labels that each got.

#1250 Backend/900/dev group
  tdrs-backend/tdpservice/settings/cloudgov.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/users/migrations/0021_add_dev_group.py
  tdrs-backend/tdpservice/users/test/test_api/test_roles.py
Labels: Ready to Merge

#1244 Issue 1012: Implement welcome page for logged-in users
  .circleci/config.yml
  tdrs-backend/wait_for_postgres.py
  tdrs-frontend/.pa11yci.json
  tdrs-frontend/nginx/locations.conf
  tdrs-frontend/src/components/LoginCallback/LoginCallback.jsx
  tdrs-frontend/src/components/LoginCallback/LoginCallback.test.js
  tdrs-frontend/src/components/NoMatch/index.js
  tdrs-frontend/src/components/Request/Request.jsx
  tdrs-frontend/src/components/Routes/Routes.js
  tdrs-frontend/src/components/Routes/Routes.test.js
  tdrs-frontend/src/components/SplashPage/SplashPage.jsx
  tdrs-frontend/src/components/SplashPage/SplashPage.test.js
  tdrs-frontend/src/components/Welcome/Welcome.jsx
  tdrs-frontend/src/components/Welcome/Welcome.test.jsx
  tdrs-frontend/src/components/Welcome/index.js
  tdrs-frontend/src/utils/signOut.js
Labels: frontend, dev, Ready to Merge, Deploy with CircleCI-raft

#1283 Round 7 docs
  docs/README.md
  docs/User-Research/2021, Summer - Communicating Errors in TDP & Validations With Regional Staff.md
  docs/User-Research/README.md
Labels: Ready to Merge

#1234 Issue 966: Add a Circle CI testing step that confirms no secret keys have been committed
  .circleci/config.yml
  .gitconfig
  regexes.json
  scripts/git-secrets-check.sh
  scripts/trufflehog-check.sh
  trufflehog-exclude-patterns.txt
Labels: dev, devops, Ready to Merge

#1243 Dynamic jwt_cert_key for unit tests
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/users/test/test_auth.py
Labels: backend, dev, Ready to Merge, DX

#1295 Issue 1296 [hotfix]: fix trufflehog scans in upstream repos
  scripts/trufflehog-check.sh
Labels: devops, Ready to Merge, Dev Top Priority

#1303 Issue 1296: Fix Trufflehog scan
  scripts/trufflehog-check.sh
Labels: devops, Dev Top Priority

#1228 [Backend] Add sys admin (1065)
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
Labels: backend, Ready to Merge

#1266 Issue 1260: Migrate Dev Deployments to Circle CI API V2
  .circleci/config.yml
  .github/workflows/deploy-on-label.yml
Labels: dev, devops, Ready to Merge, DX, ci/cd

#1294 Issue 928: Implement 404 page
  tdrs-frontend/src/assets/Button.scss
  tdrs-frontend/src/components/Header/Header.test.js
  tdrs-frontend/src/components/NavItem/NavItem.jsx
  tdrs-frontend/src/components/NoMatch/NoMatch.jsx
  tdrs-frontend/src/components/NoMatch/NoMatch.test.js
  tdrs-frontend/src/components/Routes/Routes.js
Labels: frontend, dev, Ready to Merge

#1311 New ADR for resolving 1208 and 907.
  docs/Architecture Decision Record/019-zap-waiver.md
Labels: compliance, documentation, Ready to Merge, ADR

#1317 Issue 1152: Remove upper "Sign In" link
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
Labels: frontend, dev, Ready to Merge

#1321 Issue 1291: Implement storage of ClamAV scan results
  tdrs-backend/tdpservice/core/admin.py
  tdrs-backend/tdpservice/data_files/serializers.py
  tdrs-backend/tdpservice/data_files/test/test_serializers.py
  tdrs-backend/tdpservice/data_files/validators.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-backend/tdpservice/security/__init__.py
  tdrs-backend/tdpservice/security/admin.py
  tdrs-backend/tdpservice/security/apps.py
  tdrs-backend/tdpservice/security/clients.py
  tdrs-backend/tdpservice/security/migrations/0001_initial.py
  tdrs-backend/tdpservice/security/migrations/__init__.py
  tdrs-backend/tdpservice/security/models.py
  tdrs-backend/tdpservice/security/test/__init__.py
  tdrs-backend/tdpservice/security/test/test_clamav.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/test/test_clamav.py
  tdrs-backend/tdpservice/users/migrations/0018_ofa_admin_permissions.py
  tdrs-backend/tdpservice/users/migrations/0020_ofa_system_admin_permissions.py
  tdrs-backend/tdpservice/users/migrations/0022_add_clam_av_file_scan_perms.py
  tdrs-backend/tdpservice/users/permissions.py
  tdrs-backend/tdpservice/users/test/test_permissions.py
Labels: backend, security, dev, compliance, Ready to Merge

#1242 create sprint-27-summary.md
  docs/Sprint-Review/sprint-27-summary.md
Labels: documentation, Ready to Merge

#1332 fix(1191) Codecov: Frontend uploads fail to find coverage report
  .circleci/config.yml
  codecov.yml
Labels: devops, Ready to Merge, ci/cd

#1342 Update Roadmap-and-Backlog.md
  docs/Product-Strategy/Roadmap-and-Backlog.md
Labels: Ready to Merge

#1344 Update links Current-TDRS.md
  docs/Background/Current-TDRS.md
Labels: Ready to Merge
