Repository raft-tech/TANF-app, pull requests merged in 2022-11, with the labels that each got.

#2215 fix/2140 scroll upload alert into view
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/UploadReport/UploadReport.jsx
Labels: a11y, Ready to Merge

#2230 Pin zap version to 2.11.0 for frontend scan
  tdrs-frontend/docker-compose.yml
Labels: QASP Review, Ready to Merge, Deploy with CircleCI-qasp

#2209 Fix/992 notify data file search selection changes
  tdrs-frontend/src/assets/Modal.scss
  tdrs-frontend/src/components/Button/Button.jsx
  tdrs-frontend/src/components/Modal/Modal.jsx
  tdrs-frontend/src/components/Modal/Modal.test.js
  tdrs-frontend/src/components/Modal/index.js
  tdrs-frontend/src/components/Reports/Reports.jsx
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/UploadReport/UploadReport.jsx
  tdrs-frontend/src/index.scss
Labels: Ready to Merge

#2220 Copy all Knowledge Center changes from Test env.
  product-updates/css/uswds3.css
  product-updates/img/acfofa.svg
  product-updates/img/added.svg
  product-updates/img/change.svg
  product-updates/img/changed.svg
  product-updates/img/getting-started/access-request-submitted.png
  product-updates/img/getting-started/data-submitted.png
  product-updates/img/getting-started/request-approved.png
  product-updates/img/removed.svg
  product-updates/index.html
  product-updates/knowledge-center/complete-resubmissions.html
  product-updates/knowledge-center/create-new-login.html
  product-updates/knowledge-center/existing-login.html
  product-updates/knowledge-center/give-feedback.html
  product-updates/knowledge-center/index.html
  product-updates/knowledge-center/managing-your-account.html
  product-updates/knowledge-center/uploading-data.html
Labels: Research & Design, Ready to Merge

#2249 Hotfix: Closes Knowledge center <em>'s
  product-updates/knowledge-center/create-new-login.html
  product-updates/knowledge-center/existing-login.html
  product-updates/knowledge-center/uploading-data.html
Labels: Research & Design, Ready to Merge

#2236 1755 - As a data analyst, I need to be able to upload SSP data files
  .gitignore
  tdrs-backend/docker-compose.local.yml
  tdrs-backend/docker-compose.yml
  tdrs-backend/manifest.buildpack.yml
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/serializers.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/test/test_models.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-backend/tdpservice/stts/management/commands/populate_stts.py
  tdrs-backend/tdpservice/stts/migrations/0006_alter_stt_filenames.py
  tdrs-backend/tdpservice/stts/migrations/0007_stt_ssp.py
  tdrs-backend/tdpservice/stts/models.py
  tdrs-backend/tdpservice/stts/serializers.py
  tdrs-backend/tdpservice/users/test/test_api/test_set_profile.py
  tdrs-frontend/src/actions/reports.js
  tdrs-frontend/src/components/FileUpload/FileUpload.jsx
  tdrs-frontend/src/components/Modal/Modal.test.js
  tdrs-frontend/src/components/Reports/Reports.jsx
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/Routes/Routes.js
  tdrs-frontend/src/components/UploadReport/UploadReport.jsx
  tdrs-frontend/src/reducers/reports.js
  tdrs-frontend/src/reducers/reports.test.js
Labels: Ready to Merge

#2251 Hotfix for v2.2 for SSP data submission
  tdrs-backend/tdpservice/stts/management/commands/data/states.csv
Labels: raft review, QASP Review, Deploy with CircleCI-qasp, Priority, hotfix

#2254 update buildpacks
  .circleci/config.yml
  docs/Technical-Documentation/buildpack-changelog.md
  tdrs-backend/Dockerfile
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/manifest.buildpack.yml
  tdrs-frontend/manifest.buildpack.yml
Labels: raft review, Deploy with CircleCI-raft

#2269 fix ubuntu renamed gpg key err
  .circleci/config.yml
Labels: Ready to Merge

#2270 fix ubuntu renamed gpg key err
  .circleci/config.yml
Labels: Ready to Merge

#2259 split config file with continuation orb
  .circleci/base_config.yml
  .circleci/build-and-test/commands.yml
  .circleci/build-and-test/jobs.yml
  .circleci/build-and-test/workflows.yml
  .circleci/config.yml
  .circleci/deployment/commands.yml
  .circleci/deployment/jobs.yml
  .circleci/deployment/workflows.yml
  .circleci/generate_config.sh
  .circleci/infrastructure/commands.yml
  .circleci/infrastructure/jobs.yml
  .circleci/owasp/commands.yml
  .circleci/owasp/jobs.yml
  .circleci/owasp/workflows.yml
  .circleci/util/commands.yml
  .circleci/util/jobs.yml
  .circleci/util/workflows.yml
  README.md
Labels: Deploy with CircleCI-raft

#2258 Fix/1744 permission guards
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
  tdrs-frontend/src/components/PermissionGuard/PermissionGuard.jsx
  tdrs-frontend/src/components/PermissionGuard/PermissionGuard.test.js
  tdrs-frontend/src/components/PermissionGuard/index.js
  tdrs-frontend/src/components/PrivateRoute/PrivateRoute.js
  tdrs-frontend/src/components/PrivateRoute/PrivateRoute.test.js
  tdrs-frontend/src/components/Routes/Routes.js
  tdrs-frontend/src/selectors/auth.js
Labels: Ready to Merge

#2176 Feat/1866 celery beat and postgres backups
  codecov.yml
  scripts/deploy-backend.sh
  tdrs-backend/docker-compose.local.yml
  tdrs-backend/gunicorn_start.sh
  tdrs-backend/tdpservice/scheduling/BACKUP_README.md
  tdrs-backend/tdpservice/scheduling/db_backup.py
  tdrs-backend/tdpservice/scheduling/sshkey_change.py
  tdrs-backend/tdpservice/scheduling/tasks.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/settings/local.py
Labels: dependencies, backend, dev, Ready to Merge, DX

#2287 Update 2-search-component.png (SSP/TANF & Heading change)
  product-updates/img/data-files/1-tab-emphasis.png
  product-updates/img/data-files/2-search-component.png
  product-updates/knowledge-center/uploading-data.html
Labels: Ready to Merge

#2292 Found fix for chromium bug on startup
  tdrs-frontend/Dockerfile
Labels: raft review, DX, hotfix
