Repository raft-tech/TANF-app, pull requests merged in 2022-03, with the labels that each got.

#1669 Create sprint-41-summary.md
  docs/Sprint-Review/sprint-41-summary.md
Labels: Ready to Merge

#1673 Issue 1534: Fix zap scan parameters
  .circleci/config.yml
  scripts/zap-scanner.sh
  tdrs-backend/docker-compose.yml
  tdrs-backend/reports/zap.conf
Labels: devops, Ready to Merge, ci/cd

#1657 Feat/1540 shared authentication tests
  tdrs-backend/tdpservice/users/test/test_auth.py
Labels: dev, python, Ready to Merge, authentication

#1659 Feat/1439 separate rds databases
  scripts/README.md
  scripts/deploy-backend.sh
  scripts/update-ssh-config.sh
  tdrs-backend/tdpservice/settings/cloudgov.py
Labels: Ready to Merge

#1683 Update buildpack-changelog.md
  docs/Technical-Documentation/buildpack-changelog.md
Labels: Ready to Merge

#1677 chore(react-router): Bump react-router and react-router-dom to 6.2.2
  tdrs-frontend/package-lock.json
  tdrs-frontend/package.json
Labels: dependencies, frontend, Ready to Merge

#1685 Update cloudgov.py
  tdrs-backend/tdpservice/settings/cloudgov.py
Labels: Ready to Merge

#1668 feat(1358): create default ACF OCIO permissions group
  tdrs-backend/tdpservice/users/migrations/0024_add_regional_staff_group.py
  tdrs-backend/tdpservice/users/migrations/0032_ocio_permissions_group.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/test/test_api/test_roles.py
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/LoginCallback/LoginCallback.jsx
Labels: frontend, backend, dev, Ready to Merge

#1687 Update with Steve's name
  README.md
  docs/How-We-Work/Team-Composition.md
Labels: documentation, Ready to Merge

#1648 Skip clamav locally
  commands.sh
  delete-cloudgov-docker.sh
  scripts/set-backend-env-vars.sh
  tdrs-backend/Pipfile.lock
  tdrs-backend/docker-compose.local.yml
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/data_files/validators.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-frontend/docker-compose.local.yml
Labels: dev, Ready to Merge, DX

#1688 Restore stakeholder and personas
  docs/User-Experience/README.md
  docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
  docs/User-Experience/Research-Syntheses/README.md
Labels: Research & Design, Ready to Merge

#1695 Create sprint-42-summary.md
  docs/Sprint-Review/sprint-42-summary.md
Labels: Ready to Merge

#1704 Create Sitemap Survey Research Synthesis.md
  docs/User-Experience/Research-Syntheses/Sitemap Survey Research Synthesis.md
Labels: Ready to Merge

#1675 feat(1640): optionally display the STT field based on user email address
  tdrs-frontend/src/actions/requestAccess.js
  tdrs-frontend/src/components/Home/Home.jsx
  tdrs-frontend/src/components/Home/Home.test.jsx
Labels: frontend, dev, Ready to Merge

#1712 Update team-meetings.md
  docs/How-We-Work/team-meetings.md
Labels: documentation, Ready to Merge

#1718 Create sprint-43-summary.md
  docs/Sprint-Review/sprint-43-summary.md
Labels: Ready to Merge
