Repository raft-tech/TANF-app, pull requests merged in 2022-08, with the labels that each got.

#1937 Feat/1906 use asterisk on access form
  tdrs-frontend/src/components/ComboBox/ComboBox.jsx
  tdrs-frontend/src/components/FormGroup/FormGroup.jsx
  tdrs-frontend/src/components/Home/Home.jsx
  tdrs-frontend/src/components/Home/Home.test.jsx
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/STTComboBox/STTComboBox.jsx
Labels: frontend, dev, Ready to Merge

#2011 Corrects hrefs still looking for jpegs instead of jpgs
  product-updates/knowledge-center/complete-resubmissions.html
  product-updates/knowledge-center/create-new-login.html
  product-updates/knowledge-center/existing-login.html
Labels: Ready to Merge

#2012 Updating backend FQDN per changes
  docs/Technical-Documentation/TDP-environments-README.md
Labels: documentation, Ready to Merge

#2021 Feat/1945 back out axios
  .circleci/config.yml
  .gitconfig
  scripts/deploy-backend.sh
  scripts/deploy-frontend.sh
  tdrs-backend/tdpservice/middleware.py
  tdrs-backend/tdpservice/settings/cloudgov.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-frontend/nginx/buildpack.nginx.conf
  tdrs-frontend/nginx/nginx.conf
  tdrs-frontend/src/actions/auth.js
  tdrs-frontend/src/components/GovBanner/GovBanner.jsx
  terraform/production/variables.tf
Labels: dev, devops, ci/cd, cloud

#2001 bug/1995 clamav not detecting malware
  tdrs-backend/tdpservice/settings/cloudgov.py
Labels: Ready to Merge

#1971 Feat/1754 owasp on aditional branches
  .circleci/config.yml
  scripts/zap-hook.py
  scripts/zap-scanner.sh
Labels: dev, devops, Ready to Merge

#2037 Finalizing release 2.0.0
  .circleci/config.yml
  .gitconfig
  scripts/deploy-backend.sh
  scripts/deploy-frontend.sh
  tdrs-backend/tdpservice/middleware.py
  tdrs-backend/tdpservice/settings/cloudgov.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-frontend/nginx/buildpack.nginx.conf
  tdrs-frontend/nginx/nginx.conf
  tdrs-frontend/src/actions/auth.js
  tdrs-frontend/src/components/GovBanner/GovBanner.jsx
Labels: Ready to Merge

#2041 Bug/2035 manage account button
  .circleci/config.yml
  scripts/deploy-frontend.sh
  tdrs-frontend/.env
  tdrs-frontend/.env.development
  tdrs-frontend/package.json
  tdrs-frontend/src/assets/Button.scss
  tdrs-frontend/src/components/Button/Button.jsx
  tdrs-frontend/src/components/Profile/Profile.jsx
  tdrs-frontend/src/components/Profile/Profile.test.js
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/SplashPage/SplashPage.jsx
  tdrs-frontend/src/components/SplashPage/SplashPage.test.js
Labels: Ready to Merge

#2025 Release 1 ATO documentation updates
  docs/Security-Compliance/Security-Controls/at-2/index.md
  docs/Security-Compliance/boundary-diagram.md
  docs/Security-Compliance/diagram.drawio
  docs/Security-Compliance/diagram.png
  docs/Technical-Documentation/tdp-erd.png
Labels: security, compliance, security controls, documentation, Ready to Merge

#2069 Feat/1787 site map redo
  tdrs-frontend/src/components/Footer/Footer.jsx
  tdrs-frontend/src/components/Footer/Footer.test.js
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Routes/Routes.js
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.test.js
  tdrs-frontend/src/components/SiteMap/index.js
  tdrs-frontend/src/utils/canViewAdmin.js
Labels: frontend, dev, Ready to Merge

#2070 2038 - CSRF settings Bug fix for non-production sites
  .circleci/config.yml
  scripts/deploy-backend.sh
  scripts/deploy-frontend.sh
  tdrs-backend/tdpservice/settings/cloudgov.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-frontend/nginx/buildpack.nginx.conf
  tdrs-frontend/src/actions/auth.js
  tdrs-frontend/src/components/Button/Button.jsx
  tdrs-frontend/src/components/Reports/Reports.jsx
Labels: bug, dev, Ready to Merge, techdebt
