Repository raft-tech/TANF-app, pull requests merged in 2022-06, with the labels that each got.

#1855 Create sprint-48-summary.md
  docs/Sprint-Review/sprint-48-summary.md
Labels: Ready to Merge

#1774 build(1489): Automate setting of default environment variables in Cloud.gov
  .gitconfig
  scripts/deploy-backend.sh
  scripts/set-backend-env-vars.sh
Labels: devops, Ready to Merge, techdebt

#1771 1440/s3-prefix
  .circleci/config.yml
  scripts/README.md
  scripts/sync-backend.sh
  tdrs-backend/tdpservice/backends.py
  tdrs-backend/tdpservice/settings/cloudgov.py
  tdrs-backend/tdpservice/settings/common.py
  terraform/create_backend_vars.sh
  terraform/dev/main.tf
  terraform/dev/variables.tf
  terraform/production/main.tf
  terraform/production/variables.tf
  terraform/staging/main.tf
  terraform/staging/variables.tf
Labels: backend, dev, Ready to Merge, DX

#1867 Issue 1282: Update documentation on user management
  docs/Technical-Documentation/images/admin_home.png
  docs/Technical-Documentation/images/admin_users.png
  docs/Technical-Documentation/images/group_list.png
  docs/Technical-Documentation/images/group_permissions.png
  docs/Technical-Documentation/images/stt_edit.png
  docs/Technical-Documentation/images/stt_list.png
  docs/Technical-Documentation/user_role_management.md
Labels: compliance, QASP Review, DAC, documentation, Ready to Merge

#1877 Update pull_request_template.md
  .github/pull_request_template.md
Labels: raft review, documentation

#1908 clamav was getting network policies nuked every deletion
  .circleci/config.yml
Labels: bug, dev, Ready to Merge

#1897 Create sprint-49-summary.md
  docs/Sprint-Review/sprint-49-summary.md
Labels: Ready to Merge
