Repository raft-tech/TANF-app, pull requests merged in 2022-10, with the labels that each got.

#2170 Bug/2102 label owasp scans fail
  .circleci/config.yml
  tdrs-frontend/Dockerfile
  tdrs-frontend/nginx/nginx.conf
Labels: Ready to Merge

#2129 Feat/1952 celery email queue
  tdrs-backend/docker-compose.local.yml
  tdrs-backend/tdpservice/email/__init__.py
  tdrs-backend/tdpservice/email/email.py
  tdrs-backend/tdpservice/email/email_enums.py
  tdrs-backend/tdpservice/email/templates/data-submitted.html
  tdrs-backend/tdpservice/email/test/__init__.py
  tdrs-backend/tdpservice/email/test/test_email.py
  tdrs-backend/tdpservice/settings/common.py
Labels: backend, dev, Ready to Merge

#2190 Release v2.1 update
  .circleci/config.yml
  README.md
  docs/Security-Compliance/Incidence-Response/Sys-Admin-Acct-Mgmt.md
  docs/Sprint-Review/sprint-54-summary.md
  docs/Sprint-Review/sprint-55-summary.md
  docs/Sprint-Review/sprint-56-summary.md
  docs/Technical-Documentation/Architecture-Decision-Record/005-application-authentication.md
  docs/Technical-Documentation/buildpack-changelog.md
  docs/Technical-Documentation/user_role_management.md
  docs/User-Experience/Research-Syntheses/2022, Summer - TDP 2.0 Pilot Program.md
  docs/User-Experience/Research-Syntheses/README.md
  product-updates/August-2021-Update.html
  product-updates/January-2022-Update.html
  product-updates/June-2021-Update.html
  product-updates/april-2022-update.html
  product-updates/img/complete-data/step1.jpeg
  product-updates/img/complete-data/step2-2.jpeg
  product-updates/img/complete-data/step2.jpeg
  product-updates/img/complete-data/step3.jpeg
  product-updates/img/getting-started/existing-login-homepage.jpeg
  product-updates/index.html
  product-updates/knowledge-center/complete-resubmissions.html
  product-updates/knowledge-center/create-new-login.html
  product-updates/knowledge-center/existing-login.html
  product-updates/knowledge-center/give-feedback.html
  product-updates/knowledge-center/index.html
  product-updates/knowledge-center/managing-your-account.html
  product-updates/knowledge-center/uploading-data.html
  tdrs-backend/README.md
  tdrs-backend/manifest.buildpack.yml
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-backend/tdpservice/users/migrations/0034_user_account_approval_status.py
  tdrs-backend/tdpservice/users/migrations/0035_auto_20220818_2016.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/serializers.py
  tdrs-backend/tdpservice/users/test/factories.py
  tdrs-backend/tdpservice/users/test/test_api/test_set_profile.py
  tdrs-backend/tdpservice/users/test/test_models.py
  tdrs-backend/tdpservice/users/views.py
  tdrs-frontend/Dockerfile
  tdrs-frontend/manifest.buildpack.yml
  tdrs-frontend/nginx/nginx.conf
  tdrs-frontend/src/components/Footer/Footer.test.js
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
  tdrs-frontend/src/components/Home/Home.jsx
  tdrs-frontend/src/components/Home/Home.test.jsx
  tdrs-frontend/src/components/Profile/Profile.jsx
  tdrs-frontend/src/components/Profile/Profile.test.js
  tdrs-frontend/src/components/Routes/Routes.js
  tdrs-frontend/src/components/SiteMap/SiteMap.test.js
  tdrs-frontend/src/components/UploadReport/UploadReport.test.js
  tdrs-frontend/src/selectors/auth.js
Labels: Deploy with CircleCI-sandbox

#2178 Feat/#1814 #1840 #1839 #1334 account access emails
  .circleci/config.yml
  tdrs-backend/tdpservice/email/email.py
  tdrs-backend/tdpservice/email/email_helper.py
  tdrs-backend/tdpservice/email/templates/access-request-submitted.html
  tdrs-backend/tdpservice/email/templates/account-deactivated.html
  tdrs-backend/tdpservice/email/templates/base.html
  tdrs-backend/tdpservice/email/templates/data-submitted.html
  tdrs-backend/tdpservice/email/templates/request-approved.html
  tdrs-backend/tdpservice/email/templates/request-denied.html
  tdrs-backend/tdpservice/email/test/test_email.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/test/test_account_approval_emails.py
Labels: Ready to Merge

#2101 Issue 1104: Updated boundary diagrams for release 2+
  docs/Security-Compliance/File-Transfer-TDRS/README.md
  docs/Security-Compliance/File-Transfer-TDRS/diagram.drawio
  docs/Security-Compliance/File-Transfer-TDRS/diagram.png
  docs/Security-Compliance/README.md
  docs/Security-Compliance/diagram.drawio
  docs/Security-Compliance/diagram.png
Labels: compliance, documentation, Ready to Merge

#2210 Create sprint-58-summary.md
  docs/Sprint-Review/sprint-58-summary.md
Labels: Ready to Merge

#2200 1845 - Email on data submit
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-backend/tdpservice/email/email.py
  tdrs-backend/tdpservice/email/email_enums.py
  tdrs-backend/tdpservice/email/helpers/__init__.py
  tdrs-backend/tdpservice/email/helpers/account_status.py
  tdrs-backend/tdpservice/email/helpers/data_file.py
  tdrs-backend/tdpservice/email/templates/base.html
  tdrs-backend/tdpservice/email/templates/data-submitted-failed.html
  tdrs-backend/tdpservice/email/templates/data-submitted.html
  tdrs-backend/tdpservice/users/models.py
Labels: Ready to Merge

#2221 Deps/zap broken executor
  .circleci/config.yml
Labels: Ready to Merge

#2218 Pinning version of zap2docker to 2.11.0
  tdrs-backend/docker-compose.yml
Labels: bug, dependencies, devops, Ready to Merge, hotfix
