Repository raft-tech/TANF-app, pull requests merged in 2022-09, with the labels that each got.

#1922 Update security control implementation statements
  docs/Security-Compliance/Security-Controls/ac-2/index.md
  docs/Security-Compliance/Security-Controls/ac-5/index.md
  docs/Security-Compliance/Security-Controls/ac-6/index.md
  docs/Security-Compliance/Security-Controls/ac-7/index.md
  docs/Security-Compliance/Security-Controls/au-2/index.md
  docs/Security-Compliance/Security-Controls/cm-7-2/images/clamavcm7.PNG
  docs/Security-Compliance/Security-Controls/cm-7-2/index.md
  docs/Security-Compliance/Security-Controls/ia-8/index.md
  docs/Security-Compliance/Security-Controls/ra-5/images/DAC_owasp1.PNG
  docs/Security-Compliance/Security-Controls/ra-5/images/DAC_owasp2.PNG
  docs/Security-Compliance/Security-Controls/ra-5/index.md
  docs/Security-Compliance/Security-Controls/sc-4/index.md
Labels: security controls, documentation, Ready to Merge

#2107 2054 Owasp scans copied to prod DAC
  .circleci/config.yml
  tdrs-backend/tdpservice/security/management/commands/process_owasp_scan.py
Labels: Ready to Merge

#2110 Issue 1980: Update repo readme with security policy links and prod build metrics
  .circleci/config.yml
  README.md
  docs/Technical-Documentation/Architecture-Decision-Record/005-application-authentication.md
Labels: compliance, documentation, Ready to Merge, ci/cd

#2114 Chore/restage buildpack envs
  docs/Technical-Documentation/buildpack-changelog.md
  tdrs-backend/manifest.buildpack.yml
  tdrs-frontend/manifest.buildpack.yml
Labels: Ready to Merge, Deploy with CircleCI-raft

#2147 2138 - increase pagination
  tdrs-backend/tdpservice/settings/common.py
Labels: Ready to Merge

#2143 Fix/approved with no role bug
  tdrs-frontend/src/components/Home/Home.jsx
  tdrs-frontend/src/components/UploadReport/UploadReport.test.js
  tdrs-frontend/src/selectors/auth.js
Labels: Ready to Merge

#2156 Docs/pilot synthesis
  docs/User-Experience/Research-Syntheses/2022, Summer - TDP 2.0 Pilot Program.md
  docs/User-Experience/Research-Syntheses/README.md
Labels: Research & Design, Ready to Merge

#2157 Updates & Enhancements to Project Updates / Knowledge Center
  product-updates/August-2021-Update.html
  product-updates/January-2022-Update.html
  product-updates/June-2021-Update.html
  product-updates/april-2022-update.html
  product-updates/img/complete-data/step1.jpeg
  product-updates/img/complete-data/step2-2.jpeg
  product-updates/img/complete-data/step2.jpeg
  product-updates/img/complete-data/step3.jpeg
  product-updates/img/getting-started/existing-login-homepage.jpeg
  product-updates/index.html
  product-updates/knowledge-center/complete-resubmissions.html
  product-updates/knowledge-center/create-new-login.html
  product-updates/knowledge-center/existing-login.html
  product-updates/knowledge-center/give-feedback.html
  product-updates/knowledge-center/index.html
  product-updates/knowledge-center/managing-your-account.html
  product-updates/knowledge-center/uploading-data.html
Labels: Research & Design, Ready to Merge

#2155 Feat/2136 acf titan filename from stt filename table
  tdrs-backend/tdpservice/data_files/models.py
Labels: Ready to Merge
