Repository raft-tech/TANF-app, pull requests merged in 2022-01, with the labels that each got.

#1514 Update buildpack-changelog.md
  docs/Technical-Documentation/buildpack-changelog.md
Labels: dependencies, devops, Ready to Merge

#1513 Update 011-buildpacks.md
  docs/Architecture Decision Record/011-buildpacks.md
Labels: dev, documentation, devops, Ready to Merge, DX

#1509 sprint-36-summary.md
  docs/Sprint-Review/sprint-36-summary.md
Labels: documentation, Ready to Merge

#1518 Create sprint-37-summary.md
  docs/Sprint-Review/sprint-37-summary.md
Labels: documentation, Ready to Merge

#1382 Update our-workflow.md
  docs/How-We-Work/team-charter/our-workflow.md
Labels: documentation, Ready to Merge

#1519 Update Acquisition.md
  docs/Acquisition/Acquisition.md
Labels: documentation, Ready to Merge

#1469 Update communication-tools.md
  docs/How-We-Work/team-charter/communication-tools.md
Labels: documentation, Ready to Merge

#1517 Update Team-Composition.md
  docs/How-We-Work/Team-Composition.md
Labels: documentation, Ready to Merge

#1488 Issue 1082: Updating ADRs
  docs/Architecture Decision Record/001 ADR template.md
  docs/Architecture Decision Record/002 Application architecture.md
  docs/Architecture Decision Record/003 Application hosting.md
  docs/Architecture Decision Record/005-application-authentication.md
  docs/Architecture Decision Record/006-continuous-integration.md
  docs/Architecture Decision Record/007-object-storage.md
  docs/Architecture Decision Record/008-deployment-flow.md
  docs/Architecture Decision Record/009-git-workflow.md
  docs/Architecture Decision Record/014-deploy-strategy.md
  docs/Architecture Decision Record/015-development-environments.md
  docs/Architecture Decision Record/019-zap-waiver.md
  docs/How-We-Work/Developer-Tabletops.md
  docs/Technical-Documentation/Architecture Decision Record/001 ADR template.md
  docs/Technical-Documentation/Architecture Decision Record/002 Application architecture.md
  docs/Technical-Documentation/Architecture Decision Record/003 Application hosting.md
  docs/Technical-Documentation/Architecture Decision Record/004-configuration-by-environment-variable.md
  docs/Technical-Documentation/Architecture Decision Record/005-application-authentication.md
  docs/Technical-Documentation/Architecture Decision Record/006-continuous-integration.md
  docs/Technical-Documentation/Architecture Decision Record/007-object-storage.md
  docs/Technical-Documentation/Architecture Decision Record/008-deployment-flow.md
  docs/Technical-Documentation/Architecture Decision Record/009-git-workflow.md
  docs/Technical-Documentation/Architecture Decision Record/010-assign-superuser.md
  docs/Technical-Documentation/Architecture Decision Record/011-buildpacks.md
  docs/Technical-Documentation/Architecture Decision Record/012-antivirus-strategy.md
  docs/Technical-Documentation/Architecture Decision Record/013-download-strategy.md
  docs/Technical-Documentation/Architecture Decision Record/014-dependabot-dependency-management.md
  docs/Technical-Documentation/Architecture Decision Record/015-terraform-service-provisioning.md
  docs/Technical-Documentation/Architecture Decision Record/016-zap-waiver.md
  docs/Technical-Documentation/Architecture Decision Record/images/TANF-Git-Workflow.png
Labels: documentation, Ready to Merge, ADR

#1515 Issue 1477: Updated main readme, doc structure, and secret key md
  README.md
  docs/Background/Acquisition/Acquisition.md
  docs/Background/Acquisition/COR Delegation Robert Jolly.pdf
  docs/Background/Acquisition/COR Designation Letter Lauren Frohlich - TANF.pdf
  docs/Background/Prototype/Compliance.md
  docs/Background/Prototype/Running.md
  docs/Background/Prototype/Workflows.md
  docs/Background/Prototype/updated-tanf-prototype-diagram-system.png
  docs/Security-Compliance/Secret-Key-Mgmt.md
  docs/Technical-Documentation/Architecture-Decision-Record/001-ADR-template.md
  docs/Technical-Documentation/Architecture-Decision-Record/002-Application-architecture.md
  docs/Technical-Documentation/Architecture-Decision-Record/003-Application-hosting.md
  docs/Technical-Documentation/Architecture-Decision-Record/004-configuration-by-environment-variable.md
  docs/Technical-Documentation/Architecture-Decision-Record/005-application-authentication.md
  docs/Technical-Documentation/Architecture-Decision-Record/006-continuous-integration.md
  docs/Technical-Documentation/Architecture-Decision-Record/007-object-storage.md
  docs/Technical-Documentation/Architecture-Decision-Record/008-deployment-flow.md
  docs/Technical-Documentation/Architecture-Decision-Record/009-git-workflow.md
  docs/Technical-Documentation/Architecture-Decision-Record/010-assign-superuser.md
  docs/Technical-Documentation/Architecture-Decision-Record/011-buildpacks.md
  docs/Technical-Documentation/Architecture-Decision-Record/012-antivirus-strategy.md
  docs/Technical-Documentation/Architecture-Decision-Record/013-download-strategy.md
  docs/Technical-Documentation/Architecture-Decision-Record/014-dependabot-dependency-management.md
  docs/Technical-Documentation/Architecture-Decision-Record/015-terraform-service-provisioning.md
  docs/Technical-Documentation/Architecture-Decision-Record/016-zap-waiver.md
  docs/Technical-Documentation/Architecture-Decision-Record/images/TANF-Git-Workflow.png
  docs/User-Experience/2020, Fall - Concept Prototypes/TANF Uploading Tool_Mockup #1.pdf
  docs/User-Experience/2020, Fall - Concept Prototypes/TANF Uploading Tool_Mockup #2.pdf
  docs/User-Experience/2020, Fall - Understanding STT Roles, Source of Truth, and Metadata.md
  docs/User-Experience/2020, Spring - Understanding the local experience.md
  docs/User-Experience/2020, Summer - Understanding the OFA Experience.md
  docs/User-Experience/2020, Winter - User Flow Validation/ST Workshop Facilitation Guide.md
  docs/User-Experience/2021, Spring - Evil User Journeys & TANF Data Errors (Round 6).md
  docs/User-Experience/2021, Spring - Tribal MVP (Release 2) Design Sprint.md
  docs/User-Experience/2021, Summer - Communicating Errors in TDP & Validations With Regional Staff.md
  docs/User-Experience/Design/Design-Guide.md
  docs/User-Experience/Design/Design-Principles.md
  docs/User-Experience/Design/design-assets/research-artifacts/TANF Theory of Change.png
  docs/User-Experience/Design/design-assets/research-artifacts/TDRS product plan at four levels.png
  docs/User-Experience/Design/design-assets/research-artifacts/TDRS-stakeholder-map.png
  docs/User-Experience/Design/design-assets/research-artifacts/acf_org_chart.png
  docs/User-Experience/Design/design-assets/research-artifacts/considerations to the plan.png
  docs/User-Experience/Design/design-assets/research-artifacts/three product considerations.png
  docs/User-Experience/Flat File Metadata Guide.md
  docs/User-Experience/Open research questions.md
  docs/User-Experience/Overview of Research Activities.md
  docs/User-Experience/README.md
  docs/User-Experience/STT attribute guide.md
  docs/User-Experience/Stakeholders-and-Personas.md
  docs/User-Experience/User-Research-Guide.md
  docs/User-Experience/Winter 2021, Round 4 Synthesis.md
Labels: raft review, documentation

#1437 scripts directory README documentation
  scripts/README.md
  scripts/cf-check.sh
  scripts/docker-compose-check.sh
Labels: documentation, devops, Ready to Merge

#1531 Issue 1524: security-compliance subdir updates
  docs/Security-Compliance/README.md
  docs/Security-Compliance/Secret-Key-Mgmt.md
Labels: security, documentation, Ready to Merge

#1533 Issue 1525: added readme to sprint review subdir
  docs/Sprint-Review/README.md
Labels: documentation, Ready to Merge

#1454 Fix pa11y screenshots
  tdrs-frontend/.pa11yci.json
  tdrs-frontend/src/actions/auth.js
  tdrs-frontend/src/components/PrivateTemplate/PrivateTemplate.jsx
  tdrs-frontend/src/index.js
  tdrs-frontend/src/mirage.js
Labels: frontend, devops, Ready to Merge

#1546 1269 add fall 2021 research synthesis
  docs/User-Experience/2021, Fall - Investigating Partial Submission & Evaluating TDP Submission History.md
  docs/User-Experience/README.md
Labels: Research & Design, documentation, Ready to Merge

#1369 feat(1136): Accept AMS OpenID
  codecov.yml
  docs/Technical-Documentation/remote-development.md
  tdrs-backend/.env.example
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/README.md
  tdrs-backend/docker-compose.yml
  tdrs-backend/setup.cfg
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/urls.py
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/api/login_redirect_oidc.py
  tdrs-backend/tdpservice/users/api/logout_redirect_oidc.py
  tdrs-backend/tdpservice/users/api/utils.py
  tdrs-backend/tdpservice/users/authentication.py
  tdrs-backend/tdpservice/users/migrations/0027_user_hhs_id.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/test/factories.py
  tdrs-backend/tdpservice/users/test/test_auth.py
  tdrs-backend/tdpservice/users/test/test_utils.py
  tdrs-frontend/src/components/SplashPage/SplashPage.jsx
  tdrs-frontend/src/components/SplashPage/SplashPage.test.js
Labels: backend, dev, Ready to Merge, Deploy with CircleCI-raft, authentication

#1539 Issue 1521: Updating TANF-app/doc/Background/
  docs/Background/Agency-Background.md
  docs/Background/Current-TDRS.md
  docs/Background/Prototype/Compliance.md
  docs/Background/Prototype/Running.md
  docs/Background/Prototype/Workflows.md
  docs/Background/Prototype/updated-tanf-prototype-diagram-system.png
  docs/Background/README.md
  docs/User-Experience/Research/2020, Fall - Flatfile Metadata Guide.md
  docs/User-Experience/Research/2020, Fall - Understanding STT Roles, Source of Truth, and Metadata.md
Labels: documentation, Ready to Merge

#1547 Issue 1523: Updating TANF-app/doc/How-We-Work/
  .github/pull_request_template.md
  docs/How-We-Work/Branching-Strategy.md
  docs/How-We-Work/Heuristics.md
  docs/How-We-Work/Quality-Expectations.md
  docs/How-We-Work/README.md
  docs/How-We-Work/Team-Composition.md
  docs/How-We-Work/Vendor Kick Off Week.md
  docs/How-We-Work/communication-tools.md
  docs/How-We-Work/our-priorities-values-expectations.md
  docs/How-We-Work/our-workflow.md
  docs/How-We-Work/team-charter/definition-of-done.md
  docs/How-We-Work/team-charter/manual-checks.md
  docs/How-We-Work/team-charter/our-team-and-values.md
  docs/How-We-Work/team-charter/sprint-schedule.md
  docs/How-We-Work/team-charter/team-meetings.md
  docs/How-We-Work/team-meetings.md
  docs/Technical-Documentation/how-government-will-test-a11y.md
Labels: documentation, Ready to Merge

#1542 Issue 1522: Updating TANF-app/doc/Product-Strategy/
  docs/Product-Strategy/Considerations-and-Planning.md
  docs/Product-Strategy/Prodtastic-Resources.md
  docs/Product-Strategy/README.md
  docs/Product-Strategy/Roadmap-and-Backlog.md
  docs/Product-Strategy/Vision-and-Stakeholders.md
Labels: documentation, Ready to Merge

#1554 Create sprint-38-summary.md
  docs/Sprint-Review/sprint-38-summary.md
Labels: documentation, Ready to Merge

#1536 feat(1170): Enforce AMS usage for ACF Staff
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/test/test_auth.py
Labels: backend, dev, Ready to Merge, Deploy with CircleCI-raft, authentication

#1535 Elastisearch Implementation ADR
  docs/Technical-Documentation/Architecture-Decision-Record/017-elastisearch.md
Labels: documentation, Ready to Merge

#1528 build(782): Upgrade Python to v3.10.1
  .circleci/config.yml
  scripts/trufflehog-check.sh
  tdrs-backend/Dockerfile
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: dependencies, dev, Ready to Merge

#1565 Bump Django version to 3.2.11 to address vulnerability
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: dependencies, backend, dev, Ready to Merge

#1537 build(1449): add a11y label to frontend dependabot prs
  .github/dependabot.yml
Labels: devops, Ready to Merge

#1468 fix(1419): sidenav focus issue with keyboard navigation
  tdrs-frontend/src/components/Header/Header.jsx
Labels: frontend, dev, Ready to Merge, Deploy with CircleCI-a11y

#1556 Issue 1527: Updating TANF-app/doc/User-Experience/
  docs/Background/Current-TDRS.md
  docs/User-Experience/2020, Winter - User Flow Validation/ST Workshop Facilitation Guide.md
  docs/User-Experience/Design-Principles.md
  docs/User-Experience/Design/design-assets/research-artifacts/TANF Theory of Change.png
  docs/User-Experience/Design/design-assets/research-artifacts/TDRS product plan at four levels.png
  docs/User-Experience/Design/design-assets/research-artifacts/TDRS-stakeholder-map.png
  docs/User-Experience/Design/design-assets/research-artifacts/acf_org_chart.png
  docs/User-Experience/Design/design-assets/research-artifacts/considerations to the plan.png
  docs/User-Experience/Design/design-assets/research-artifacts/three product considerations.png
  docs/User-Experience/Dev-Ready-Designs/README.md
  docs/User-Experience/Open research questions.md
  docs/User-Experience/Overview of Research Activities.md
  docs/User-Experience/README.md
  docs/User-Experience/Research-Syntheses/2020, Fall - Flatfile Metadata Guide.md
  docs/User-Experience/Research-Syntheses/2020, Fall - STT Attribute Guide.md
  docs/User-Experience/Research-Syntheses/2020, Fall - Understanding STT Roles, Source of Truth, and Metadata.md
  docs/User-Experience/Research-Syntheses/2020, Fall - Understanding STT and OFA painpoints.md
  docs/User-Experience/Research-Syntheses/2020, Spring - Understanding the local experience.md
  docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
  docs/User-Experience/Research-Syntheses/2020, Summer - Understanding the OFA Experience.md
  docs/User-Experience/Research-Syntheses/2021, Fall - Investigating Partial Submission & Evaluating TDP Submission History.md
  docs/User-Experience/Research-Syntheses/2021, Spring - Evil User Journeys & TANF Data Errors.md
  docs/User-Experience/Research-Syntheses/2021, Spring - Tribal MVP (Release 2) Design Sprint.md
  docs/User-Experience/Research-Syntheses/2021, Summer - Communicating Errors in TDP & Validations With Regional Staff.md
  docs/User-Experience/Research-Syntheses/README.md
  docs/User-Experience/Research-Syntheses/TANF Uploading Tool_Mockup #1.pdf
  docs/User-Experience/Research-Syntheses/TANF Uploading Tool_Mockup #2.pdf
  docs/User-Experience/Style-Guide.md
  docs/User-Experience/UX-markdown-practices.md
Labels: documentation, Ready to Merge

#1538 build(854): switch frontend package manager from yarn to npm
  .circleci/config.yml
  docs/Technical-Documentation/circle-ci.md
  scripts/deploy-frontend.sh
  tdrs-frontend/Dockerfile
  tdrs-frontend/README.md
  tdrs-frontend/docker-compose.local.yml
  tdrs-frontend/package-lock.json
  tdrs-frontend/package.json
  tdrs-frontend/yarn.lock
  trufflehog-exclude-patterns.txt
Labels: frontend, dev, Ready to Merge, Deploy with CircleCI-sandbox

#1516 build(1413): Django Admin tooltip improvements for wider compatibility
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: dev, a11y, Ready to Merge, Deploy with CircleCI-a11y

#1548 Feat/1545 (part 2) Setup deployment for live comms site
  .circleci/config.yml
  live-comms/August-2021-Update.html
  live-comms/CONTRIBUTING.md
  live-comms/June-2021-Update.html
  live-comms/README.md
  live-comms/Staticfile
  live-comms/css/uswds.css
  live-comms/fonts/merriweather/Latin-Merriweather-Bold.woff2
  live-comms/fonts/merriweather/Latin-Merriweather-Regular.woff2
  live-comms/fonts/source-sans-pro/sourcesanspro-bold-webfont.woff2
  live-comms/fonts/source-sans-pro/sourcesanspro-regular-webfont.woff2
  live-comms/index.html
  live-comms/manifest.yml
  scripts/README.md
  scripts/deploy-live-comms.sh
Labels: Ready to Merge

#1586 hotfix(1545) live comms deploy script should be executable
  scripts/deploy-live-comms.sh
Labels: dev, Ready to Merge
