Repository raft-tech/TANF-app, pull requests merged in 2022-02, with the labels that each got.

#1549 Feat (470): Script commands for development operations
  commands.sh
Labels: frontend, backend, dev, Ready to Merge, DX

#1599 Update team-meetings.md
  docs/How-We-Work/team-meetings.md
Labels: documentation, Ready to Merge

#1598 Create sprint-39-summary.md
  docs/Sprint-Review/sprint-39-summary.md
Labels: documentation, Ready to Merge

#1597 1595 font fixes for live comms
  live-comms/August-2021-Update.html
  live-comms/June-2021-Update.html
  live-comms/README.md
  live-comms/fonts/merriweather/Latin-Merriweather-Regular.ttf
  live-comms/fonts/merriweather/Latin-Merriweather-Regular.woff
  live-comms/fonts/source-sans-pro/sourcesanspro-bold-webfont.ttf
  live-comms/fonts/source-sans-pro/sourcesanspro-bold-webfont.woff
  live-comms/index.html
Labels: Ready to Merge

#1600 Hotfix/1170 Ensure user session is created after email is verified
  tdrs-backend/tdpservice/users/api/login.py
Labels: bug, backend, dev, Ready to Merge, authentication

#1603 Change domain from live-comms to product-updates
  .circleci/config.yml
  scripts/deploy-tdp-product-update-site.sh
Labels: raft review

#1611 Update 009-git-workflow.md
  docs/Technical-Documentation/Architecture-Decision-Record/009-git-workflow.md
Labels: Ready to Merge

#1615 Create README.md
  docs/Technical-Documentation/README.md
Labels: documentation, Ready to Merge

#1622 Removing redundant request for ACs
  .github/pull_request_template.md
Labels: documentation, Ready to Merge

#1639 Create sprint-40-summary.md
  docs/Sprint-Review/sprint-40-summary.md
Labels: documentation, Ready to Merge

#1654 Tweaking migration and shell script for backend vars
  scripts/set-backend-env-vars.sh
  tdrs-backend/tdpservice/users/migrations/0031_remove_federal_gov_stt.py
Labels: backend, dev, Ready to Merge, Deploy with CircleCI-a11y

#1635 Bump Django and ipython
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: backend, Ready to Merge

#1656 Revert "Bump Django and ipython"
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: Ready to Merge

#1663 Update sprint-40-summary.md
  docs/Sprint-Review/sprint-40-summary.md
Labels: documentation, Ready to Merge
