Repository raft-tech/TANF-app, pull requests merged in 2023-04, with the labels that each got.

#2468 Create sprint-69-summary.md
  docs/Sprint-Review/sprint-69-summary.md
Labels: Ready to Merge

#2471 Filter User by STT/Region
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/test/test_models.py
Labels: backend, dev, raft review

#2462 2408.2 - refactor preparser
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/preparser.py
  tdrs-backend/tdpservice/parsers/schema_defs/__init__.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/schema_defs/trailer.py
  tdrs-backend/tdpservice/parsers/schema_defs/universal.py
  tdrs-backend/tdpservice/parsers/test/data/bad_trailer_1.txt
  tdrs-backend/tdpservice/parsers/test/data/bad_trailer_2.txt
  tdrs-backend/tdpservice/parsers/test/test_data_parsing.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
Labels: Ready to Merge, Deploy with CircleCI-sandbox

#2476 Filter Users by STT/Region
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/test/test_models.py
Labels: backend, dev, Ready to Merge

#2464 2408.3 - refactor tanf t1 parsing
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/schema_defs/__init__.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/__init__.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: Ready to Merge

#2483 2482 - Split location in the DAC user list so that stt/region can be sorted
  tdrs-backend/tdpservice/users/admin.py
Labels: raft review, Ready to Merge

#2475 1113.0 - Chore/reorganize search indexes
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/tanf_parser.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/search_indexes/admin/__init__.py
  tdrs-backend/tdpservice/search_indexes/admin/ssp.py
  tdrs-backend/tdpservice/search_indexes/admin/tanf.py
  tdrs-backend/tdpservice/search_indexes/admin/tribal.py
  tdrs-backend/tdpservice/search_indexes/documents/__init__.py
  tdrs-backend/tdpservice/search_indexes/documents/ssp.py
  tdrs-backend/tdpservice/search_indexes/documents/tanf.py
  tdrs-backend/tdpservice/search_indexes/documents/tribal.py
  tdrs-backend/tdpservice/search_indexes/migrations/0006_auto_20230403_1957.py
  tdrs-backend/tdpservice/search_indexes/models/__init__.py
  tdrs-backend/tdpservice/search_indexes/models/ssp.py
  tdrs-backend/tdpservice/search_indexes/models/tanf.py
  tdrs-backend/tdpservice/search_indexes/models/tribal.py
  tdrs-backend/tdpservice/search_indexes/test/test_model_mapping.py
  tdrs-backend/tdpservice/users/test/test_permissions.py
Labels: Ready to Merge

#2495 BUG FIX correction or zap-scanner URLs
  scripts/zap-scanner.sh
Labels: bug, devops, Priority

#2492 Fix/pipeline failures
  .circleci/build-and-test/jobs.yml
  .circleci/util/jobs.yml
Labels: raft review

#2493 Update TDP-environments-README.md
  docs/Technical-Documentation/TDP-environments-README.md
Labels: documentation, Ready to Merge

#2496 BUG FIX - added develop to acf.hhs.gov domain in zap-scanner
  scripts/zap-scanner.sh
Labels: bug, devops, Ready to Merge, ci/cd

#2472 updating csv file columns after talking with ux
  tdrs-backend/tdpservice/parsers/models.py
  tdrs-backend/tdpservice/parsers/test/factories.py
  tdrs-backend/tdpservice/parsers/test/test_serializer.py
  tdrs-backend/tdpservice/parsers/views.py
Labels: dev, Ready to Merge
