Repository raft-tech/TANF-app, pull requests merged in 2023-01, with the labels that each got.

#2333 Create sprint-63-summary.md
  docs/Sprint-Review/sprint-63-summary.md
Labels: Ready to Merge

#2271 No more robots
  tdrs-frontend/public/robots.txt
Labels: Ready to Merge

#2348 Only prod shall have prod vars
  .github/workflows/deploy-on-label.yml
  scripts/deploy-backend.sh
Labels: Deploy with CircleCI-a11y

#2359 Update Sys-Admin-Acct-Mgmt.md
  .github/workflows/qasp-owasp-scan.yml
  docs/Security-Compliance/Incidence-Response/Sys-Admin-Acct-Mgmt.md
Labels: security, compliance, documentation, Ready to Merge

#2339 January project update
  product-updates/August-2021-Update.html
  product-updates/August-2022-Update.html
  product-updates/January-2022-Update.html
  product-updates/June-2021-Update.html
  product-updates/april-2022-update.html
  product-updates/dist/lity.css
  product-updates/dist/lity.js
  product-updates/dist/lity.min.css
  product-updates/dist/lity.min.js
  product-updates/img/jan-update-2023/bug.png
  product-updates/img/jan-update-2023/request-access-form.png
  product-updates/img/jan-update-2023/section-optional.png
  product-updates/index.html
Labels: Research & Design, Ready to Merge

#2361 Create sprint-64-summary.md
  docs/Sprint-Review/sprint-64-summary.md
Labels: Ready to Merge

#2362 Driver/navigator raft reviews
  docs/Technical-Documentation/Architecture-Decision-Record/009-git-workflow.md
Labels: documentation

#2363 Feat/217 revise stt model
  tdrs-backend/tdpservice/scheduling/test/test_file_upload.py
  tdrs-backend/tdpservice/stts/admin.py
  tdrs-backend/tdpservice/stts/management/commands/populate_stts.py
  tdrs-backend/tdpservice/stts/migrations/0008_auto_20230118_1623.py
  tdrs-backend/tdpservice/stts/migrations/0009_stt_sample.py
  tdrs-backend/tdpservice/stts/models.py
  tdrs-backend/tdpservice/stts/serializers.py
  tdrs-backend/tdpservice/stts/test/factories.py
  tdrs-backend/tdpservice/stts/test/test_api.py
  tdrs-backend/tdpservice/stts/test/test_commands.py
Labels: Ready to Merge

#2367 Issue 2336: Documentation added for CircleCI IR
  docs/Security-Compliance/Incidence-Response/CircleCI-IRP.md
  docs/Security-Compliance/Incidence-Response/README.md
  docs/Technical-Documentation/secret-key-rotation-steps.md
Labels: security, compliance, Ready to Merge, ci/cd

#2305 Chore/2141 cypress
  .circleci/build-and-test/jobs.yml
  .circleci/build-and-test/workflows.yml
  .gitignore
  docs/Technical-Documentation/Architecture-Decision-Record/019-integration-tests.md
  docs/Technical-Documentation/cypress-integration-tests.md
  docs/Technical-Documentation/images/testing/01-e2e-selection.png
  docs/Technical-Documentation/images/testing/02-browser-selection.png
  docs/Technical-Documentation/images/testing/03-spec-selection.png
  docs/Technical-Documentation/images/testing/04-run-test.png
  tdrs-backend/.env.example
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/urls.py
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/management/commands/generate_cypress_users.py
  tdrs-frontend/cypress.config.js
  tdrs-frontend/cypress/e2e/accounts/accounts.feature
  tdrs-frontend/cypress/e2e/accounts/steps.js
  tdrs-frontend/cypress/support/commands.js
  tdrs-frontend/cypress/support/e2e.js
  tdrs-frontend/package-lock.json
  tdrs-frontend/package.json
  tdrs-frontend/src/index.js
Labels: Ready to Merge

#2378 Added George Hudson (DevOps - Raft)
  docs/How-We-Work/Team-Composition.md
Labels: Ready to Merge

#2372 1609 Submission History
  .circleci/deployment/workflows.yml
  tdrs-backend/gunicorn_start.sh
  tdrs-backend/tdpservice/backends.py
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/s3_client.py
  tdrs-backend/tdpservice/data_files/serializers.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-frontend/package-lock.json
  tdrs-frontend/package.json
  tdrs-frontend/src/actions/reports.js
  tdrs-frontend/src/assets/Reports.scss
  tdrs-frontend/src/components/FileUpload/FileUpload.jsx
  tdrs-frontend/src/components/Paginator/Paginator.jsx
  tdrs-frontend/src/components/Paginator/Paginator.test.js
  tdrs-frontend/src/components/Paginator/index.js
  tdrs-frontend/src/components/Reports/Reports.jsx
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/SegmentedControl/SegmentedControl.jsx
  tdrs-frontend/src/components/SegmentedControl/SegmentedControl.test.js
  tdrs-frontend/src/components/SegmentedControl/index.js
  tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.jsx
  tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.test.js
  tdrs-frontend/src/components/SubmissionHistory/index.js
  tdrs-frontend/src/components/UploadReport/UploadReport.jsx
  tdrs-frontend/src/components/UploadReport/UploadReport.test.js
  tdrs-frontend/src/reducers/reports.js
  tdrs-frontend/src/reducers/reports.test.js
Labels: raft review, Deploy with CircleCI-raft

#2377 132 - Converted field names per Alex, gov lead
  tdrs-backend/Dockerfile
  tdrs-backend/docker-compose.local.yml
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/search_indexes/admin.py
  tdrs-backend/tdpservice/search_indexes/documents.py
  tdrs-backend/tdpservice/search_indexes/migrations/0002_standardized_field_names.py
  tdrs-backend/tdpservice/search_indexes/migrations/003_auto_20230127_1553.py
  tdrs-backend/tdpservice/search_indexes/models.py
  tdrs-backend/tdpservice/search_indexes/parsers/schema_defs/tanf.py
  tdrs-backend/tdpservice/search_indexes/test/test_model_mapping.py
Labels: backend, dev, Ready to Merge, database
