Repository raft-tech/TANF-app, pull requests merged in 2023-03, with the labels that each got.

#2428 Fixing logout flow
  tdrs-backend/tdpservice/users/api/logout_redirect_oidc.py
Labels: bug, backend, Ready to Merge, DX, authentication

#2440 Feat/1965 approved user homepage
  tdrs-frontend/src/components/Home/Home.jsx
  tdrs-frontend/src/components/Home/Home.test.jsx
  tdrs-frontend/src/components/Reports/Reports.jsx
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/ResourceCards/ResourceCards.jsx
  tdrs-frontend/src/components/ResourceCards/ResourceCards.test.js
  tdrs-frontend/src/components/ResourceCards/index.js
  tdrs-frontend/src/components/SplashPage/SplashPage.jsx
  tdrs-frontend/src/components/SplashPage/SplashPage.test.js
  tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.jsx
Labels: Ready to Merge

#2444 Bug 2379 search form error count
  tdrs-frontend/src/components/Reports/Reports.jsx
Labels: Ready to Merge

#2451 remove reports useEffect
  tdrs-frontend/src/App.js
Labels: raft review

#2453 Create CloudFoundry-DB-Connection.md
  docs/Technical-Documentation/CloudFoundry-DB-Connection.md
Labels: raft review

#2455 Downgrading to within HHS limits.
  .circleci/base_config.yml
Labels: Ready to Merge

#2388 Updates UX templates to include internal raft-review AC
  .github/ISSUE_TEMPLATE/design-deliverable-issue-template.md
  .github/ISSUE_TEMPLATE/research-synthesis-issue-template.md
Labels: Research & Design, raft review

#2446 Fix/1641 stt code in user
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-backend/tdpservice/stts/admin.py
  tdrs-backend/tdpservice/stts/models.py
  tdrs-backend/tdpservice/stts/test/test_models.py
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/migrations/0036_auto_20230306_1431.py
  tdrs-backend/tdpservice/users/migrations/0037_auto_20230306_1434.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/serializers.py
  tdrs-backend/tdpservice/users/test/factories.py
  tdrs-backend/tdpservice/users/test/test_models.py
  tdrs-backend/tdpservice/users/views.py
Labels: Ready to Merge

#2450 Fix/2443 admin link in sitemap
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.test.js
  tdrs-frontend/src/selectors/auth.js
  tdrs-frontend/src/utils/canViewAdmin.js
Labels: Ready to Merge

#2459 March Knowledge Center Updates
  product-updates/img/usa-icons/info.svg
  product-updates/knowledge-center/faq.html
  product-updates/knowledge-center/index.html
Labels: Research & Design, Ready to Merge, a11y-review
