Repository raft-tech/TANF-app, pull requests merged in 2023-12, with the labels that each got.

#2727 2683-zap-CORS-misconfig
  scripts/deploy-backend.sh
  scripts/deploy-frontend.sh
  scripts/zap-scanner.sh
  tdrs-backend/clamav-router/nginx.conf
  tdrs-backend/tdpservice/settings/cloudgov.py
  tdrs-frontend/nginx/cloud.gov/locations.conf
Labels: security, compliance, devops, Ready to Merge

#2748 Fix parser/preparser validation of empty strings
  tdrs-backend/tdpservice/parsers/fields.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: Ready to Merge

#2765 added needed space into logic
  docs/Security-Compliance/boundary-diagram.md
  scripts/deploy-backend.sh
Labels: Ready to Merge

#2778 Datafile Parse Latency Bug
  tdrs-backend/tdpservice/parsers/models.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: bug, backend, Ready to Merge, spike

#2763 adding documentation on cloudgov s3 incident response
  docs/Security-Compliance/Incidence-Response/Cloudgov-S3-IRP-Oct2023.md
  docs/Security-Compliance/Incidence-Response/README.md
Labels: security, compliance, documentation, Ready to Merge

#2734 2599-error-report-excel-format
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/tdpservice/parsers/fields.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/trailer.py
  tdrs-backend/tdpservice/parsers/test/data/small_incorrect_file_cross_validator.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/test/test_views.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators.py
  tdrs-backend/tdpservice/parsers/views.py
  tdrs-frontend/nginx/cloud.gov/locations.conf
Labels: backend, Ready to Merge

#2770 Issue 2488: boundary diagram updates
  docs/Security-Compliance/File-Transfer-TDRS/diagram.drawio
  docs/Security-Compliance/File-Transfer-TDRS/diagram.png
  docs/Security-Compliance/boundary-diagram.md
  docs/Security-Compliance/diagram.drawio
  docs/Security-Compliance/diagram.png
Labels: security, compliance, documentation, Ready to Merge

#2786 added Tom's workaround for files changed in windows auto changing whe…
  .gitattributes
Labels: Ready to Merge

#2787 updated terraform to add redis service instances
  terraform/dev/main.tf
  terraform/dev/variables.tf
Labels: Ready to Merge
