Repository raft-tech/TANF-app, pull requests merged in 2023-11, with the labels that each got.

#2730 Update cloudgov.py
  scripts/deploy-backend.sh
  tdrs-backend/tdpservice/settings/cloudgov.py
Labels: Ready to Merge

#2728 Create sprint-83-summary.md
  docs/Sprint-Review/sprint-83-summary.md
Labels: Ready to Merge

#2737 Sprint 84 summary
  docs/Sprint-Review/sprint-84-summary.md
Labels: Ready to Merge

#2743 Debug/develop deployment failures
  scripts/deploy-backend.sh
Labels: Ready to Merge

#2725 File Input Render Issue
  tdrs-frontend/nginx/cloud.gov/buildpack.nginx.conf
  tdrs-frontend/nginx/local/default.conf.template
Labels: bug, dev, a11y, Ready to Merge

#2704 2695 field spaces
  tdrs-backend/tdpservice/parsers/fields.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/test/data/tanf_section1_blanks.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: backend, dev, Ready to Merge

#2720 Infinite FETCH_STTS
  tdrs-frontend/src/components/STTComboBox/STTComboBox.jsx
Labels: frontend, dev, a11y, Ready to Merge

#2723 Feature/2709 ssp section 1 validation
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/test/data/small_ssp_section1.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: raft review, Ready to Merge

#2741 allow circleci tdrs-run-deploy to kick off with new functionality
  commands.sh
Labels: Ready to Merge

#2682 added documentation for our Nexus repository
  docs/Technical-Documentation/README.md
  docs/Technical-Documentation/nexus-repo.md
Labels: Ready to Merge

#2750 Create sprint-85-summary.md
  docs/Sprint-Review/sprint-85-summary.md
Labels: documentation

#2733 Feature/1119 ssp section 3
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/__init__.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/test/data/ADS.E2J.NDM3.MS24
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/search_indexes/admin/__init__.py
  tdrs-backend/tdpservice/search_indexes/admin/ssp.py
  tdrs-backend/tdpservice/search_indexes/documents/ssp.py
  tdrs-backend/tdpservice/search_indexes/migrations/0019_ssp_m6.py
  tdrs-backend/tdpservice/search_indexes/models/ssp.py
  tdrs-backend/tdpservice/search_indexes/test/test_model_mapping.py
  tdrs-backend/tdpservice/users/test/test_permissions.py
Labels: Ready to Merge

#2752 Create sprint-86-summary.md
  docs/Sprint-Review/sprint-86-summary.md
Labels: documentation

#2758 Fixing the link ( removing the "copy" from the file name
  docs/User-Experience/Research-Syntheses/2023, Winter - TDP 3.0 Pilot Program.md
Labels: documentation, Ready to Merge

#2760 add file size to clamav-nginx
  tdrs-backend/clamav-router/nginx.conf
Labels: Ready to Merge
