Repository raft-tech/TANF-app, pull requests merged in 2024-02, with the labels that each got.

#2831 2768 - Pass ZAP pipeline, discard return code
  scripts/zap-scanner.sh
Labels: Ready to Merge

#2830 Create sprint-91-summary.md
  docs/Sprint-Review/sprint-91-summary.md
Labels: Ready to Merge

#2775 Proof of Concept TDP Based Kibana Auth
  .circleci/build-and-test/jobs.yml
  .circleci/util/commands.yml
  tdrs-backend/docker-compose.yml
  tdrs-backend/elastic_setup/Dockerfile
  tdrs-backend/elastic_setup/entrypoint.sh
  tdrs-backend/elastic_setup/util.sh
  tdrs-backend/kibana.yml
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/urls.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-frontend/nginx/local/locations.conf
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
  tdrs-frontend/src/selectors/auth.js
Labels: backend, dev, Ready to Merge, authentication

#2832 Accessibility Guide
  docs/Technical-Documentation/README.md
  docs/Technical-Documentation/accessibility-guide.md
  docs/Technical-Documentation/rafts-accessibility-dos-and-donts.md
Labels: a11y, documentation, Ready to Merge

#2805 Kibana Deployment
  .circleci/deployment/commands.yml
  .gitconfig
  scripts/deploy-backend.sh
  scripts/deploy-frontend.sh
  tdrs-backend/clamav-router/nginx.conf
  tdrs-backend/docker-compose.yml
  tdrs-backend/kibana.yml
  tdrs-backend/manifest.kibana.yml
  tdrs-backend/manifest.proxy.yml
  tdrs-backend/tdpservice/search_indexes/documents/document_base.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/urls.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-frontend/.env
  tdrs-frontend/docker-compose.yml
  tdrs-frontend/manifest.buildpack.yml
  tdrs-frontend/manifest.yml
  tdrs-frontend/nginx/cloud.gov/buildpack.nginx.conf
  tdrs-frontend/nginx/cloud.gov/locations.conf
  tdrs-frontend/nginx/local/default.conf.template
  tdrs-frontend/nginx/local/locations.conf
  tdrs-frontend/src/components/Home/Home.jsx
  tdrs-frontend/src/components/STTComboBox/STTComboBox.jsx
  tdrs-frontend/src/selectors/auth.js
Labels: backend, devops, Ready to Merge, ci/cd, authentication

#2834 Case Number Validators
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: backend, dev, Ready to Merge, spike

#2827 Feat/2813 reduce dev env
  .circleci/README.md
  docs/Technical-Documentation/Architecture-Decision-Record/008-deployment-flow.md
  docs/Technical-Documentation/TDP-environments-README.md
  docs/Technical-Documentation/diagrams/tdp-environments.drawio
  docs/Technical-Documentation/diagrams/tdp-environments.drawio.png
  scripts/update-ssh-config.sh
  terraform/dev/variables.tf
Labels: Ready to Merge

#2829 SSN Cat2 Updates
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/test/data/small_bad_tanf_s1.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: backend, dev, raft review, Ready to Merge

#2836 Fix XSS vulnerability (pentest findings)
  tdrs-frontend/src/components/FileUpload/utils.jsx
  tdrs-frontend/src/utils/escapeHtml.js
  tdrs-frontend/src/utils/escapeHtml.test.js
Labels: Ready to Merge

#2828 Feat/2768 zap pipeline
  .circleci/owasp/jobs.yml
  tdrs-backend/tdpservice/security/management/commands/process_owasp_scan.py
Labels: Ready to Merge

#2841 Fix Insecure Direct Object Reference in parser error report download (pentest findings)
  tdrs-backend/tdpservice/data_files/serializers.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/util.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-backend/tdpservice/parsers/test/test_views.py
  tdrs-backend/tdpservice/parsers/urls.py
  tdrs-backend/tdpservice/parsers/views.py
  tdrs-backend/tdpservice/urls.py
  tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.jsx
Labels: Ready to Merge

#2835 Handle elastic BulkIndexException in bulk_create_records
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: Ready to Merge

#2853 DB Backup Bug
  tdrs-backend/tdpservice/email/tasks.py
  tdrs-backend/tdpservice/scheduling/db_backup.py
  tdrs-backend/tdpservice/scheduling/tasks.py
  tdrs-backend/tdpservice/scheduling/test/test_user_deactivation_warning.py
  tdrs-backend/tdpservice/settings/common.py
  terraform/dev/main.tf
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: bug, backend, devops, Ready to Merge, Priority, database
