Repository raft-tech/TANF-app, pull requests merged in 2024-05, with the labels that each got.

#2900 Sprint 95 summary
  docs/Sprint-Review/sprint-95-summary.md
Labels: documentation, Ready to Merge

#2972 Adds contributing & code of conduct markdowns
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
Labels: Research & Design, documentation, Ready to Merge

#2856 2757-generate-preparser-error-multi-record-wrong-length
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/test/factories.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: backend, dev, Ready to Merge

#2979 Multi Filter Error
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: dependencies, backend, dev, raft review, DAC

#2981 Sprint 97 Summary
  docs/Sprint-Review/sprint-97-summary.md
Labels: Ready to Merge

#2988 [bugfix] 2987 update zap docker image to 2.14.0
  tdrs-backend/docker-compose.yml
  tdrs-frontend/docker-compose.yml
Labels: bug

#2959 2509 - Data submission email
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-backend/tdpservice/email/helpers/data_file.py
  tdrs-backend/tdpservice/email/helpers/test/test_data_file.py
  tdrs-backend/tdpservice/email/templates/data-submitted.html
  tdrs-backend/tdpservice/scheduling/parser_task.py
Labels: Ready to Merge

#2952 Quick PR to Merge Priority Changes from `friendlynamefixes2`
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
Labels: Ready to Merge

#2859 Cat 4 implementation cont'd - records are related validator
  .circleci/util/commands.yml
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/migrations/0011_parsererror_row_number_optional.py
  tdrs-backend/tdpservice/parsers/models.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/test/factories.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
Labels: Ready to Merge

#2881 2870 elastic reindex customizations
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/core/utils.py
  tdrs-backend/tdpservice/email/email.py
  tdrs-backend/tdpservice/email/helpers/account_deactivation_warning.py
  tdrs-backend/tdpservice/email/helpers/account_status.py
  tdrs-backend/tdpservice/search_indexes/management/__init__.py
  tdrs-backend/tdpservice/search_indexes/management/commands/__init__.py
  tdrs-backend/tdpservice/search_indexes/management/commands/seed_records.py
  tdrs-backend/tdpservice/search_indexes/management/commands/tdp_search_index.py
  tdrs-backend/tdpservice/search_indexes/tasks.py
  tdrs-backend/tdpservice/settings/common.py
Labels: Ready to Merge, Parity

#2945 2884 preparser errors multi record rows wrong length missing space filled m3 tribal t3
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t3.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: backend, dev, python, Ready to Merge, Parity

#2912 Space Fill Checks for T1's, T4's, M1, and M4 Records
  tdrs-backend/tdpservice/parsers/aggregates.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/test/data/aggregates_rejected.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: backend, dev, Ready to Merge, Parity

#2989 Add service discoverability for backend routes
  tdrs-frontend/nginx/cloud.gov/locations.conf
  tdrs-frontend/nginx/local/locations.conf
Labels: Ready to Merge

#2941 2238 document unsafe-inline exception
  docs/Technical-Documentation/Architecture-Decision-Record/016-security-scan-waiver.md
Labels: Ready to Merge

#2983 2949 - export file rename
  tdrs-backend/tdpservice/search_indexes/admin/mixins.py
Labels: Ready to Merge

#2970 Unify Duplicate Detection Across Program Types
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: backend, dev, raft review, Parity

#2961 2938 blank filled ssn not parsing throws NoneType error
  tdrs-backend/tdpservice/parsers/test/test_transforms.py
  tdrs-backend/tdpservice/parsers/transforms.py
Labels: bug, backend, Ready to Merge

#2955 2688 tanf section 2 validation clean up
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/test/data/small_tanf_section2.txt
  tdrs-backend/tdpservice/parsers/test/test_header.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: backend, Ready to Merge

#3005 DAC Filtering Error
  tdrs-frontend/nginx/cloud.gov/locations.conf
  tdrs-frontend/nginx/local/locations.conf
Labels: bug, frontend, dev, DAC, Ready to Merge, techdebt

#2951 2749 ftanf validation checks
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/data/ADS.E2J.FTP2.TS142.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_transforms.py
  tdrs-backend/tdpservice/parsers/transforms.py
  tdrs-backend/tdpservice/parsers/validators.py
  tdrs-backend/tdpservice/search_indexes/migrations/0028_education_level_to_string.py
  tdrs-backend/tdpservice/search_indexes/models/ssp.py
Labels: backend, dev, Ready to Merge, techdebt

#2967 2901 generate auth token
  tdrs-backend/docs/api/authentication.md
  tdrs-backend/tdpservice/security/test/test_views.py
  tdrs-backend/tdpservice/security/urls.py
  tdrs-backend/tdpservice/security/utils.py
  tdrs-backend/tdpservice/security/views.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/urls.py
Labels: backend, Ready to Merge, TDP Admin
