Repository raft-tech/TANF-app, pull requests merged in 2024-10, with the labels that each got.

#3202 3180 - error type field
  tdrs-backend/tdpservice/data_files/util.py
Labels: Ready to Merge

#3211 Whitespace Hotfix
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: Deploy with CircleCI-raft, hotfix

#3165 Nexus MVP
  .circleci/base_config.yml
  .circleci/build-and-test/commands.yml
  .circleci/build-and-test/jobs.yml
  .circleci/deployment/commands.yml
  .circleci/deployment/jobs.yml
  .circleci/deployment/workflows.yml
  .circleci/generate_config.sh
  .circleci/owasp/jobs.yml
  docs/Technical-Documentation/images/nexus-dev-admin-login.png
  docs/Technical-Documentation/nexus-repo.md
  scripts/build-and-tag-images.sh
  tdrs-backend/docker-compose.yml
  tdrs-frontend/docker-compose.yml
Labels: dev, devops, Ready to Merge, DX

#3195 2990 - stuck files notification
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/tasks.py
  tdrs-backend/tdpservice/data_files/test/test_stuck_files.py
  tdrs-backend/tdpservice/email/email_enums.py
  tdrs-backend/tdpservice/email/helpers/data_file.py
  tdrs-backend/tdpservice/email/templates/stuck-file-list.html
  tdrs-backend/tdpservice/parsers/test/factories.py
  tdrs-backend/tdpservice/search_indexes/test/test_reparse.py
  tdrs-backend/tdpservice/settings/common.py
Labels: Ready to Merge

#3134 Feat/2965 db seed impl
  .gitignore
  Taskfile.yml
  tdrs-backend/tdpservice/parsers/management/__init__.py
  tdrs-backend/tdpservice/parsers/management/commands/__init__.py
  tdrs-backend/tdpservice/parsers/management/commands/seed_db.py
Labels: backend, devops, DX

#3216 3.6.4 release notes and KC updates
  product-updates/img/error-reports/error-report.png
  product-updates/knowledge-center/index.html
  product-updates/knowledge-center/viewing-error-reports.html
Labels: Ready to Merge

#3204 Additional DF Filters
  tdrs-backend/tdpservice/data_files/admin/admin.py
  tdrs-backend/tdpservice/data_files/admin/filters.py
  tdrs-backend/tdpservice/data_files/models.py
Labels: backend, dev, DAC, Ready to Merge

#3226 Hotfix/make erd docker login
  .circleci/build-and-test/workflows.yml
  .circleci/util/jobs.yml
  tdrs-backend/docker-compose.yml
  tdrs-backend/setup.cfg
Labels: bug, devops

#3220 3157 - Reparse Meta through model
  tdrs-backend/tdpservice/data_files/admin/admin.py
  tdrs-backend/tdpservice/data_files/admin/filters.py
  tdrs-backend/tdpservice/data_files/migrations/0014_reparsefilemeta.py
  tdrs-backend/tdpservice/data_files/migrations/0015_datafile_reparses.py
  tdrs-backend/tdpservice/data_files/migrations/0016_remove_datafile_reparse_meta_models.py
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/tasks.py
  tdrs-backend/tdpservice/data_files/test/test_stuck_files.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/test/factories.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
  tdrs-backend/tdpservice/search_indexes/admin/reparse_meta.py
  tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py
  tdrs-backend/tdpservice/search_indexes/management/commands/tdp_search_index.py
  tdrs-backend/tdpservice/search_indexes/migrations/0032_auto_20241008_1745.py
  tdrs-backend/tdpservice/search_indexes/models/reparse_meta.py
  tdrs-backend/tdpservice/search_indexes/test/test_reparse.py
  tdrs-backend/tdpservice/users/test/test_permissions.py
Labels: Ready to Merge

#3229 3109 - Quarter Explainer
  tdrs-frontend/src/components/Reports/Reports.jsx
Labels: Ready to Merge, Deploy with CircleCI-raft

#3167 3106 reparse django action
  tdrs-backend/tdpservice/data_files/admin/admin.py
  tdrs-backend/tdpservice/data_files/static/admin/js/admin/admin_datafile_model.js
  tdrs-backend/tdpservice/data_files/tasks.py
  tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py
Labels: Ready to Merge

#3239 Release notes 3.7.0
  product-updates/knowledge-center/exporting-complete-data-using-ftanf.html
  product-updates/knowledge-center/index.html
  product-updates/knowledge-center/uploading-data.html
Labels: Ready to Merge

#3214 Update personas document for issue #3100
  docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
Labels: Ready to Merge

#3200 Feat/3171 nexus integration
  .circleci/build-and-test/commands.yml
  Taskfile.yml
  scripts/cf-check.sh
  tdrs-backend/Dockerfile
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/sources.list
  tdrs-frontend/package-lock.json
Labels: Ready to Merge

#3210 Doc/3199 monitoring adr
  docs/Security-Compliance/diagram.drawio
  docs/Security-Compliance/diagram.png
  docs/Technical-Documentation/Architecture-Decision-Record/022-app-monitoring.md
  docs/Technical-Documentation/diagrams/TDP_Environments.png
  docs/Technical-Documentation/images/sentry/1. Issues with filter enabled.png
  docs/Technical-Documentation/images/sentry/2. Unhandled exceptiions are logged.png
  docs/Technical-Documentation/images/sentry/3. detail about exception.png
  docs/Technical-Documentation/images/sentry/4. full stack trace of the exceptions.png
Labels: Ready to Merge, OCIO Review

#3247 Fixes doc formatting issue
  docs/User-Experience/Research-Syntheses/2020, Summer - Understanding Stakeholders and creating personas.md
Labels: documentation, Ready to Merge
