Repository raft-tech/TANF-app, pull requests merged in 2024-08, with the labels that each got.

#3063 Create sprint-102-summary.md
  docs/Sprint-Review/sprint-102-summary.md
Labels: Ready to Merge

#3105 sprint-103-summary.md
  README.md
  docs/Sprint-Review/sprint-103-summary.md
Labels: Ready to Merge

#3127 Update READMEs re: dev envs
  README.md
  docs/Technical-Documentation/TDP-environments-README.md
Labels: Ready to Merge

#3124 1646 - aria label mismatch
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
Labels: Ready to Merge

#3132 Delete tdrs-backend/tdpservice/parsers/schema_defs/util.py
  tdrs-backend/tdpservice/parsers/schema_defs/util.py
Labels: raft review

#3129 Bug: Fix REC_SSI Cat4 Validator
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
Labels: bug, backend, dev, Ready to Merge, Priority

#3130 3113 added validation skip error
  tdrs-backend/tdpservice/parsers/fields.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/test/test_header.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: backend, dev, Ready to Merge, P4

#3125 Issue 3033: Updating range for FQ validator
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
Labels: bug, backend, Ready to Merge

#3071 1621 descriptive error message in error response
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/templates/error_pages/500.html
  tdrs-backend/tdpservice/users/api/login.py
  tdrs-backend/tdpservice/users/api/login_redirect_oidc.py
  tdrs-backend/tdpservice/users/test/test_api/test_login.py
  tdrs-backend/tdpservice/users/test/test_auth.py
Labels: Ready to Merge

#3080 Parse Exception Handling
  tdrs-backend/Dockerfile
  tdrs-backend/tdpservice/email/email.py
  tdrs-backend/tdpservice/email/helpers/data_file.py
  tdrs-backend/tdpservice/email/test/test_email.py
  tdrs-backend/tdpservice/parsers/models.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
Labels: bug, backend, dev, Ready to Merge

#3131 DB Backup Script Fix
  scripts/deploy-backend.sh
  tdrs-backend/tdpservice/scheduling/management/db_backup.py
Labels: bug, backend, dev, Ready to Merge

#3020 2954 - Remove SESSION_TIMEOUT
  tdrs-backend/docs/session-management.md
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/users/api/middleware.py
  tdrs-backend/tdpservice/users/api/utils.py
  tdrs-backend/tdpservice/users/test/test_auth.py
Labels: Ready to Merge

#3083 DAC Filter A11y Compliance
  tdrs-backend/Dockerfile
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/tdpservice/search_indexes/admin/filters.py
  tdrs-backend/tdpservice/search_indexes/admin/multiselect_filter.py
  tdrs-backend/tdpservice/search_indexes/templates/multiselectdropdownfilter.html
  tdrs-backend/tdpservice/settings/common.py
Labels: dependencies, backend, dev, DAC, Ready to Merge, Gov A11y Review

#3148 3.5.2 release notes
  product-updates/knowledge-center/index.html
  product-updates/knowledge-center/viewing-error-reports.html
Labels: QASP Review, Ready to Merge

#3136 3065 -Sequential Reparse
  tdrs-backend/tdpservice/data_files/admin.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/search_indexes/admin/reparse_meta.py
  tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py
  tdrs-backend/tdpservice/settings/common.py
Labels: backend, dev, raft review, DAC, Deploy with CircleCI-a11y

#3051 Dynamic Cat4 Error Messages
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/duplicate_manager.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/test_case_consistency.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: backend, dev, Blocked, Ready to Merge

#3126 3064 -Reparse Meta Model
  docs/Technical-Documentation/clean-and-reparse.md
  tdrs-backend/gunicorn_start.sh
  tdrs-backend/tdpservice/data_files/admin/__init__.py
  tdrs-backend/tdpservice/data_files/admin/admin.py
  tdrs-backend/tdpservice/data_files/admin/filters.py
  tdrs-backend/tdpservice/data_files/migrations/0013_datafile_reparse_meta.py
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/test/test_admin.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
  tdrs-backend/tdpservice/search_indexes/admin/__init__.py
  tdrs-backend/tdpservice/search_indexes/admin/reparse_meta.py
  tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py
  tdrs-backend/tdpservice/search_indexes/management/commands/tdp_search_index.py
  tdrs-backend/tdpservice/search_indexes/migrations/0030_reparse_meta_model.py
  tdrs-backend/tdpservice/search_indexes/models/__init__.py
  tdrs-backend/tdpservice/search_indexes/models/reparse_meta.py
  tdrs-backend/tdpservice/search_indexes/util.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/users/test/test_permissions.py
Labels: backend, dev, DAC, Ready to Merge

#3122 2792 - Cat 3 error message cleanup
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/fields.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/trailer.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators.py
  tdrs-backend/tdpservice/parsers/validators/__init__.py
  tdrs-backend/tdpservice/parsers/validators/base.py
  tdrs-backend/tdpservice/parsers/validators/category1.py
  tdrs-backend/tdpservice/parsers/validators/category2.py
  tdrs-backend/tdpservice/parsers/validators/category3.py
  tdrs-backend/tdpservice/parsers/validators/test/__init__.py
  tdrs-backend/tdpservice/parsers/validators/test/test_base.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category1.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category2.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category3.py
  tdrs-backend/tdpservice/parsers/validators/util.py
Labels: Ready to Merge

#3160 Refreshed environments to show ES/ClamAV updates from earlier this year
  docs/Technical-Documentation/diagrams/tdp-environments.drawio
  docs/Technical-Documentation/diagrams/tdp-environments.drawio.png
Labels: Ready to Merge

#3153 2910 Synthesis
  docs/User-Experience/Research-Syntheses/2024, Summer - OFA Admin Experience.md
  docs/User-Experience/Research-Syntheses/README.md
Labels: Research & Design, documentation, Ready to Merge

#3133 Create sprint-104-summary.md
  docs/Sprint-Review/sprint-104-summary.md
Labels: Ready to Merge

#3150 Create sprint-105-summary.md
  docs/Sprint-Review/sprint-105-summary.md
Labels: Ready to Merge
