Repository raft-tech/TANF-app, pull requests merged in 2024-11, with the labels that each got.

#3272 Update cf-check.sh
  scripts/cf-check.sh
Labels: bug, devops, Deploy with CircleCI-raft

#3260 3141 - fix cypress
  tdrs-frontend/cypress/e2e/common-steps/common-steps.js
Labels: raft review

#3283 PG Apt Repo Hotfix
  tdrs-backend/Dockerfile
Labels: backend, hotfix

#3246 HHS Env Vars Mismatch
  scripts/deploy-backend.sh
Labels: backend, dev, devops, Ready to Merge, techdebt

#3231 3014 - Outdated submissions banner
  tdrs-backend/tdpservice/data_files/serializers.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-frontend/src/components/SubmissionHistory/CaseAggregatesTable.jsx
  tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.jsx
  tdrs-frontend/src/components/SubmissionHistory/TotalAggregatesTable.jsx
  tdrs-frontend/src/components/SubmissionHistory/helpers.jsx
  tdrs-frontend/src/reducers/reports.js
Labels: Ready to Merge

#3252 Local Alertmanager MVP
  tdrs-backend/docker-compose.yml
  tdrs-backend/plg/alertmanager/alertmanager.yml
  tdrs-backend/plg/alertmanager/manifest.yml
  tdrs-backend/plg/grafana/dashboards/logs_dashboard.json
  tdrs-backend/plg/prometheus/alerts.local.yml
  tdrs-backend/plg/prometheus/alerts.yml
  tdrs-backend/plg/prometheus/django-rules.yml
  tdrs-backend/plg/prometheus/prometheus.local.yml
  tdrs-backend/plg/prometheus/prometheus.yml
  tdrs-backend/tdpservice/urls.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-frontend/docker-compose.yml
  tdrs-frontend/nginx/local/locations.conf
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
  tdrs-frontend/src/selectors/auth.js
Labels: frontend, backend, dev, devops, Ready to Merge

#3275 2562 - Per-file parsing log, tech memo
  docs/Technical-Documentation/tech-memos/parsing-log-per-file/parsing-log-per-file.md
Labels: raft review

#3312 transparent boundary diagram background
  docs/Security-Compliance/diagram.png
Labels: Ready to Merge
