Repository raft-tech/TANF-app, pull requests merged in 2024-04, with the labels that each got.

#2861 DIGIT Team Group + Kibana + Queries
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-backend/tdpservice/users/migrations/0040_users_digit_group_permissions.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/test/test_api/test_roles.py
  tdrs-backend/tdpservice/users/test/test_permissions.py
  tdrs-frontend/src/selectors/auth.js
Labels: backend, dev, DAC, Ready to Merge

#2907 Error categories guide
  docs/Technical-Documentation/README.md
  docs/Technical-Documentation/error-categories-guide.md
Labels: Research & Design, documentation, Ready to Merge

#2838 Cat1 Cleanup
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/header.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/trailer.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/validators.py
  tdrs-backend/tdpservice/settings/common.py
Labels: backend, dev, Ready to Merge

#2880 Change handling of elastic BulkIndexError
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: Ready to Merge

#2911 2822 fix webinspect medium priority - persistent session
  tdrs-backend/tdpservice/settings/common.py
Labels: Ready to Merge

#2898 2887 - 18A REC_OASDI_INSURANCE not mandatory
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/test/data/ssp_section2_rec_oadsi_file.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: Ready to Merge

#2876 2814-aggregate-cloud-gov-ES-instances
  docs/Technical-Documentation/create-elastic-kibana.md
  scripts/create-es-kibana.sh
  scripts/deploy-backend.sh
  scripts/deploy-frontend.sh
  tdrs-backend/tdpservice/search_indexes/documents/ssp.py
  tdrs-backend/tdpservice/search_indexes/documents/tanf.py
  tdrs-backend/tdpservice/search_indexes/documents/tribal.py
  tdrs-backend/tdpservice/settings/cloudgov.py
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/settings/local.py
Labels: devops, Ready to Merge, cloud

#2932 1349 automate elastic search using terraform
  terraform/README.md
  terraform/dev/main.tf
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: raft review, devops, Ready to Merge

#2939 Zap Fix
  .circleci/build-and-test/jobs.yml
  .circleci/build-and-test/workflows.yml
  .circleci/deployment/jobs.yml
  .circleci/owasp/jobs.yml
  .circleci/util/jobs.yml
  scripts/zap-scanner.sh
Labels: bug, dev, devops, Ready to Merge, ci/cd, Parity

#2915 DAC CSV Export
  tdrs-backend/tdpservice/search_indexes/admin/filter.py
  tdrs-backend/tdpservice/search_indexes/admin/filters.py
  tdrs-backend/tdpservice/search_indexes/admin/mixins.py
  tdrs-backend/tdpservice/search_indexes/admin/ssp.py
  tdrs-backend/tdpservice/search_indexes/admin/tanf.py
  tdrs-backend/tdpservice/search_indexes/admin/tribal.py
  tdrs-backend/tdpservice/search_indexes/templates/multiselectlistfilter.html
Labels: backend, dev, DAC, Ready to Merge, Parity

#2889 2807 quarter validate
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
  tdrs-backend/tdpservice/parsers/test/data/ADS.E2J.FTP3.TS06
  tdrs-backend/tdpservice/parsers/test/data/ADS.E2J.FTP3.TS142
  tdrs-backend/tdpservice/parsers/test/data/ADS.E2J.FTP4.TS06
  tdrs-backend/tdpservice/parsers/test/data/ADS.E2J.NDM3.MS24
  tdrs-backend/tdpservice/parsers/test/data/ADS.E2J.NDM4.MS24
  tdrs-backend/tdpservice/parsers/test/data/tanf_section4_with_errors.txt
  tdrs-backend/tdpservice/parsers/test/data/tribal_section_4_fake.txt
  tdrs-backend/tdpservice/parsers/test/data/tribal_section_4_fake_bad_quarter.txt
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_validators.py
  tdrs-backend/tdpservice/parsers/transforms.py
  tdrs-backend/tdpservice/parsers/validators.py
Labels: Ready to Merge

#2903 Nginx DNS Issue: Kibana and ClamAV
  .circleci/build-and-test/jobs.yml
  .circleci/util/commands.yml
  tdrs-backend/clamav-router/nginx.conf
  tdrs-backend/docker-compose.yml
  tdrs-backend/elastic_setup/Dockerfile
  tdrs-backend/elastic_setup/entrypoint.sh
  tdrs-backend/elastic_setup/util.sh
  tdrs-frontend/nginx/README.md
  tdrs-frontend/nginx/cloud.gov/buildpack.nginx.conf
  tdrs-frontend/nginx/cloud.gov/locations.conf
  tdrs-frontend/nginx/local/default.conf.template
  tdrs-frontend/nginx/local/locations.conf
Labels: backend, dev, devops, Ready to Merge, Parity

#2958 Create sprint-96-summary.md
  docs/Sprint-Review/sprint-96-summary.md
Labels: QASP Review, Ready to Merge
