Repository raft-tech/TANF-app, pull requests merged in 2024-09, with the labels that each got.

#3101 3043 Sentry local
  Taskfile.yml
  sentry/.env
  sentry/backup.json
  sentry/docker-compose.yml
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/tdpservice/settings/local.py
Labels: raft review

#3169 Bugfix remove ipdb
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
Labels: Deploy with CircleCI-raft

#3158 3074 TDP Datafile page for DIGIT and Sys Admin groups
  Taskfile.yml
  tdrs-backend/tdpservice/users/migrations/0041_users_digit_group_add_datafile_permission.py
  tdrs-backend/tdpservice/users/test/test_permissions.py
  tdrs-frontend/src/components/Reports/Reports.jsx
Labels: backend, Ready to Merge

#3145 2561 Deactivating inactive user automatically
  tdrs-backend/tdpservice/email/email_enums.py
  tdrs-backend/tdpservice/email/helpers/account_deactivation_warning.py
  tdrs-backend/tdpservice/email/helpers/admin_notifications.py
  tdrs-backend/tdpservice/email/tasks.py
  tdrs-backend/tdpservice/email/templates/account-deactivated-admin.html
  tdrs-backend/tdpservice/scheduling/test/test_user_deactivation_warning.py
  tdrs-backend/tdpservice/settings/common.py
Labels: backend, Ready to Merge

#3166 sprint-106-summary.md
  docs/Sprint-Review/sprint-106-summary.md
Labels: Ready to Merge

#3146 3076 admin filter enhancement
  tdrs-backend/tdpservice/data_files/admin/admin.py
  tdrs-backend/tdpservice/data_files/test/test_admin.py
Labels: Ready to Merge, a11y-review

#3139 3087 - Datafile newest filter
  tdrs-backend/tdpservice/core/filters.py
  tdrs-backend/tdpservice/data_files/admin/admin.py
  tdrs-backend/tdpservice/data_files/admin/filters.py
  tdrs-backend/tdpservice/search_indexes/admin/filters.py
Labels: Ready to Merge

#3178 3.6.0 release notes
  product-updates/knowledge-center/index.html
  product-updates/knowledge-center/view-submission-history.html
  product-updates/knowledge-center/viewing-error-reports.html
Labels: Ready to Merge

#3154 Spike: Multi-Select Filter Integration
  docs/Technical-Documentation/tech-memos/multi-select-fiters/multi-select-filters.md
  docs/Technical-Documentation/tech-memos/multi-select-fiters/multiselectdropdownfilter.html
  docs/Technical-Documentation/tech-memos/tm-template.md
Labels: dependencies, backend, dev, raft review, DAC

#3185 TANF S3/S4 Total Number of Families Validator Update
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: backend, dev, Ready to Merge

#3174 Local PLG MVP
  tdrs-backend/docker-compose.yml
  tdrs-backend/plg/grafana/dashboards/loki_test_dashboard.json
  tdrs-backend/plg/grafana/datasources.yml
  tdrs-backend/plg/promtail/config.yml
  tdrs-backend/tdpservice/settings/common.py
  tdrs-frontend/docker-compose.yml
  tdrs-frontend/nginx/local/default.conf.template
Labels: frontend, backend, dev, raft review

#3186 Update dev-issue-template.md
  .github/ISSUE_TEMPLATE/dev-issue-template.md
  docs/How-We-Work/team-meetings.md
Labels: Ready to Merge

#3163 Prometheus & Grafana
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/docker-compose.yml
  tdrs-backend/plg/grafana/custom.ini
  tdrs-backend/plg/grafana/dashboards/django_dashboard.json
  tdrs-backend/plg/grafana/dashboards/loki_test_dashboard.json
  tdrs-backend/plg/grafana/dashboards/postgres_dashboard.json
  tdrs-backend/plg/grafana/dashboards/provider.yml
  tdrs-backend/plg/grafana/datasources.yml
  tdrs-backend/plg/postgres-exporter/deploy.sh
  tdrs-backend/plg/postgres-exporter/manifest.yml
  tdrs-backend/plg/prometheus/django_rules.yml
  tdrs-backend/plg/prometheus/prometheus.yml
  tdrs-backend/plg/promtail/config.yml
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/urls.py
  tdrs-backend/tdpservice/users/api/authorization_check.py
  tdrs-frontend/.env
  tdrs-frontend/docker-compose.yml
  tdrs-frontend/nginx/local/default.conf.template
  tdrs-frontend/nginx/local/locations.conf
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
  tdrs-frontend/src/selectors/auth.js
Labels: backend, dev, raft review, devops

#3162 #3137 (+ #3138) - worker crash/timeout on csv export
  tdrs-backend/tdpservice/search_indexes/admin/mixins.py
  tdrs-backend/tdpservice/search_indexes/tasks.py
Labels: Ready to Merge

#3198 Deploy Hotfix: Log File Path
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/settings/common.py
Labels: bug, dev, raft review, Deploy with CircleCI-raft, hotfix, P5

#3184 AMS Logout Redirect Bug Fix
  tdrs-backend/tdpservice/users/api/logout_redirect_oidc.py
Labels: bug, backend, dev, Ready to Merge

#3203 PG Client Hotfix
  tdrs-backend/Dockerfile
Labels: Ready to Merge, Deploy with CircleCI-raft, hotfix

#3189 Create sprint-107-summary.md
  docs/Sprint-Review/sprint-107-summary.md
Labels: documentation, Ready to Merge

#3172 Reparse Memory Management
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/parsers/parse.py
  tdrs-backend/tdpservice/parsers/test/factories.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/validators/category3.py
  tdrs-backend/tdpservice/scheduling/management/db_backup.py
  tdrs-backend/tdpservice/scheduling/test/test_db_backup.py
  tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py
  tdrs-backend/tdpservice/search_indexes/models/reparse_meta.py
  tdrs-backend/tdpservice/search_indexes/test/test_model_mapping.py
  tdrs-backend/tdpservice/search_indexes/test/test_reparse.py
  terraform/dev/main.tf
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: bug, backend, dev, Ready to Merge
