Repository raft-tech/TANF-app, pull requests merged in 2025-09, with the labels that each got.

#5312 5226 e2e tests for non data analyst submissions
  tdrs-backend/tdpservice/fixtures/cypress/users.json
  tdrs-frontend/cypress/e2e/common-steps/common-steps.js
  tdrs-frontend/cypress/e2e/common-steps/data_files.js
  tdrs-frontend/cypress/e2e/data-files/file_upload.feature
  tdrs-frontend/cypress/e2e/data-files/file_upload.js
Labels: frontend, raft review

#5311 Create sprint-131-summary.md
  docs/Sprint-Review/sprint-131-summary.md
Labels: Ready to Merge

#5348 3515 bug ofa system admin users get stuck region assigned
  tdrs-backend/tdpservice/users/admin.py
Labels: raft review, Refined

#5379 TANF Program Audit Tech Memos
  docs/Technical-Documentation/tech-memos/database-duplicate-detection.md
  docs/Technical-Documentation/tech-memos/type_casting.md
Labels: backend, dev, raft review, Priority
