Repository raft-tech/TANF-app, pull requests merged in 2025-04, with the labels that each got.

#3545 3455 simplified m2 t2 SSN validator
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category3.py
Labels: Ready to Merge

#4576 Error Report Download
  tdrs-backend/tdpservice/data_files/serializers.py
Labels: bug, frontend, backend, dev, QASP Review, snacks, UX Review

#3513 FRA Error Report
  tdrs-backend/tdpservice/data_files/error_reports.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/util.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-backend/tdpservice/parsers/aggregates.py
  tdrs-backend/tdpservice/parsers/case_consistency_validator.py
  tdrs-backend/tdpservice/parsers/fields.py
  tdrs-backend/tdpservice/parsers/fra_parser.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/schema_defs/fra/te1.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/test/test_util.py
  tdrs-backend/tdpservice/parsers/util.py
  tdrs-backend/tdpservice/parsers/validators/category1.py
  tdrs-backend/tdpservice/parsers/validators/category2.py
  tdrs-backend/tdpservice/scheduling/parser_task.py
Labels: backend, dev, QASP Review

#3577 3484 add flag and update validation rules for states participating in the fra pilot
  tdrs-backend/Pipfile
  tdrs-backend/Pipfile.lock
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/test/data/tanf_pilot_state.txt
  tdrs-backend/tdpservice/parsers/validators/category3.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category3.py
  tdrs-backend/tdpservice/settings/common.py
Labels: backend, dev, QASP Review

#4476 Celery Exporter
  tdrs-backend/docker-compose.yml
  tdrs-backend/gunicorn_start.sh
  tdrs-backend/plg/alertmanager/alertmanager.yml
  tdrs-backend/plg/deploy.sh
  tdrs-backend/plg/grafana/dashboards/health.json
  tdrs-backend/plg/prometheus/alerts.yml
  tdrs-backend/plg/prometheus/prometheus.local.yml
  tdrs-backend/plg/prometheus/prometheus.yml
  tdrs-backend/plg/promtail/config.yml
  tdrs-backend/tdpservice/settings/common.py
  tdrs-backend/tdpservice/settings/local.py
Labels: QASP Review, devops

#3518 Latest DataFile Only
  tdrs-backend/tdpservice/scheduling/datafile_retention_tasks.py
  tdrs-backend/tdpservice/scheduling/management/commands/remove_all_old_df_versions.py
  tdrs-backend/tdpservice/scheduling/tasks.py
  tdrs-backend/tdpservice/search_indexes/util.py
  tdrs-backend/tdpservice/search_indexes/utils.py
  tdrs-backend/tdpservice/settings/common.py
Labels: backend, dev, Ready to Merge

#4613 Gov Banner Visual Issue
  tdrs-frontend/src/components/GovBanner/GovBanner.jsx
Labels: bug, frontend, dev, Ready to Merge, snacks

#3563 FRA Cat4 Integration
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/parsers/aggregates.py
  tdrs-backend/tdpservice/parsers/base_parser.py
  tdrs-backend/tdpservice/parsers/duplicate_detectors.py
  tdrs-backend/tdpservice/parsers/duplicate_manager.py
  tdrs-backend/tdpservice/parsers/fra_parser.py
  tdrs-backend/tdpservice/parsers/models.py
  tdrs-backend/tdpservice/parsers/row_schema.py
  tdrs-backend/tdpservice/parsers/tdr_parser.py
  tdrs-backend/tdpservice/parsers/test/data/fra_ofa_test.csv
  tdrs-backend/tdpservice/parsers/test/data/fra_ofa_test.xlsx
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/util.py
Labels: backend, dev, Ready to Merge

#4631 FRA Knowledge Center Pages
  product-updates/img/fra/change-file.png
  product-updates/img/fra/error-report.png
  product-updates/img/fra/search.png
  product-updates/img/fra/submission-history.png
  product-updates/img/fra/submission-unfilled.png
  product-updates/img/fra/submission.png
  product-updates/knowledge-center/fra-error-reports.html
  product-updates/knowledge-center/submitting-fra-data.html
Labels: QASP Review

#3975 Mimir Integration
  .gitconfig
  scripts/localstack-setup.sh
  tdrs-backend/docker-compose.yml
  tdrs-backend/plg/deploy.sh
  tdrs-backend/plg/grafana/custom.local.ini
  tdrs-backend/plg/grafana/dashboards/django_dashboard.json
  tdrs-backend/plg/grafana/dashboards/health.json
  tdrs-backend/plg/grafana/dashboards/logs_dashboard.json
  tdrs-backend/plg/grafana/datasources.local.yml
  tdrs-backend/plg/grafana/datasources.template.yml
  tdrs-backend/plg/mimir/manifest.yml
  tdrs-backend/plg/mimir/mimir.local.yml
  tdrs-backend/plg/mimir/mimir.yml
  tdrs-backend/plg/prometheus/alerts.local.yml
  tdrs-backend/plg/prometheus/alerts.yml
  tdrs-backend/plg/prometheus/prometheus.local.yml
  tdrs-backend/plg/prometheus/prometheus.yml
Labels: devops, Ready to Merge

#4871 Patch FRA Excel Formula Field Parsing
  tdrs-backend/tdpservice/parsers/decoders.py
  tdrs-backend/tdpservice/parsers/test/conftest.py
  tdrs-backend/tdpservice/parsers/test/data/fra_formula_fields.xlsx
  tdrs-backend/tdpservice/parsers/test/test_parse.py
Labels: Ready to Merge

#4867 KC updates for april release
  product-updates/knowledge-center/index.html
Labels: QASP Review

#4313 4448 - Fix submission history first load bug
  tdrs-frontend/src/actions/fraReports.test.js
  tdrs-frontend/src/components/Reports/FRAReports.jsx
  tdrs-frontend/src/components/Reports/FRAReports.test.js
Labels: Ready to Merge, hotfix

#4575 3291 - Add tribes
  tdrs-backend/tdpservice/stts/management/commands/data/tribes.csv
Labels: Ready to Merge

#4320 3556 - Convert fra submission filename on download
  tdrs-backend/tdpservice/data_files/s3_client.py
  tdrs-frontend/src/actions/fraReports.js
  tdrs-frontend/src/actions/reports.js
  tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.test.js
  tdrs-frontend/src/components/SubmissionHistory/helpers.jsx
Labels: Ready to Merge

#4890 Minimum Record Length
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m1.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m4.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m6.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t7.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t1.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t4.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t6.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t7.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/parsers/validators/category1.py
  tdrs-backend/tdpservice/parsers/validators/test/test_category1.py
Labels: Ready to Merge

#4894 3529 remove elastic kibana from deployement
  tdrs-backend/docker-compose.yml
  terraform/dev/main.tf
  terraform/production/main.tf
  terraform/staging/main.tf
Labels: raft review
