Repository raft-tech/TANF-app, pull requests merged in 2025-02, with the labels that each got.

#3412 3397 fra report types data file model
  tdrs-backend/tdpservice/data_files/migrations/0017_alter_datafile_section.py
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/serializers.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/test/test_models.py
  tdrs-backend/tdpservice/data_files/views.py
Labels: backend, Ready to Merge

#3451 Hotfix/3450 rename gender to sex
  CODE_OF_CONDUCT.md
  Taskfile.yml
  docs/User-Experience/Research-Syntheses/2020, Spring - Understanding the local experience.md
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py
  tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t2.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t3.py
  tdrs-backend/tdpservice/parsers/schema_defs/tribal_tanf/t5.py
  tdrs-backend/tdpservice/parsers/test/factories.py
  tdrs-backend/tdpservice/parsers/test/test_parse.py
  tdrs-backend/tdpservice/search_indexes/documents/ssp.py
  tdrs-backend/tdpservice/search_indexes/documents/tanf.py
  tdrs-backend/tdpservice/search_indexes/documents/tribal.py
  tdrs-backend/tdpservice/search_indexes/kibana_saved_objs.ndjson
  tdrs-backend/tdpservice/search_indexes/migrations/0033_auto_20250131_2033.py
  tdrs-backend/tdpservice/search_indexes/models/ssp.py
  tdrs-backend/tdpservice/search_indexes/models/tanf.py
  tdrs-backend/tdpservice/search_indexes/models/tribal.py
  tdrs-backend/tdpservice/search_indexes/test/test_model_mapping.py
Labels: Ready to Merge

#3433 Create sprint-112-summary.md
  docs/Sprint-Review/sprint-112-summary.md
Labels: Ready to Merge

#3434 Create sprint-113-summary.md
  docs/Sprint-Review/sprint-113-summary.md
Labels: Ready to Merge

#3435 Create sprint-114-summary.md
  docs/Sprint-Review/sprint-114-summary.md
Labels: Ready to Merge

#3436 Create sprint-115-summary.md
  docs/Sprint-Review/sprint-115-summary.md
Labels: Ready to Merge

#3437 Create sprint-116-summary.md
  docs/Sprint-Review/sprint-116-summary.md
Labels: Ready to Merge

#3448 Create sprint-117-summary.md
  docs/Sprint-Review/sprint-117-summary.md
Labels: Ready to Merge

#3438 Updated File Upload to Auto Encode to UTF-8
  tdrs-frontend/package-lock.json
  tdrs-frontend/package.json
  tdrs-frontend/src/actions/reports.js
  tdrs-frontend/src/components/FileUpload/FileUpload.jsx
  tdrs-frontend/src/components/Reports/Reports.test.js
  tdrs-frontend/src/components/UploadReport/UploadReport.test.js
  tdrs-frontend/src/setupTests.js
Labels: frontend, dev, Ready to Merge

#3452 Parser Refactor Tech Memo
  docs/Technical-Documentation/tech-memos/parsing-refactor/parsing-refactor.md
Labels: backend, dev, raft review, documentation

#3430 3399 controlled access fra data files page
  Taskfile.yml
  tdrs-backend/tdpservice/data_files/admin/admin.py
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/views.py
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/migrations/0042_user_feature_flags.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/test/test_models.py
  tdrs-frontend/cypress/e2e/accounts/accounts.js
Labels: backend, Ready to Merge

#3425 3.7.7 release notes
  product-updates/img/extension/error.png
  product-updates/knowledge-center/index.html
  product-updates/knowledge-center/viewing-error-reports.html
Labels: raft review

#3440 Regional User Request Access
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/email/helpers/account_status.py
  tdrs-backend/tdpservice/email/templates/access-request-submitted.html
  tdrs-backend/tdpservice/email/templates/request-approved.html
  tdrs-backend/tdpservice/stts/management/commands/data/regions.csv
  tdrs-backend/tdpservice/stts/management/commands/populate_stts.py
  tdrs-backend/tdpservice/stts/migrations/0011_add_region_name.py
  tdrs-backend/tdpservice/stts/models.py
  tdrs-backend/tdpservice/stts/test/test_models.py
  tdrs-backend/tdpservice/users/admin.py
  tdrs-backend/tdpservice/users/migrations/0043_create_regions_m2m_del_region.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/permissions.py
  tdrs-backend/tdpservice/users/serializers.py
  tdrs-backend/tdpservice/users/test/factories.py
  tdrs-backend/tdpservice/users/test/test_api/test_users.py
  tdrs-backend/tdpservice/users/test/test_models.py
  tdrs-backend/tdpservice/users/views.py
  tdrs-frontend/cypress/e2e/accounts/accounts.js
  tdrs-frontend/cypress/e2e/common-steps/common-steps.js
  tdrs-frontend/src/actions/requestAccess.js
  tdrs-frontend/src/components/Home/Home.jsx
  tdrs-frontend/src/components/Home/Home.test.jsx
  tdrs-frontend/src/components/RequestAccessForm/JurisdictionSelector.jsx
  tdrs-frontend/src/components/RequestAccessForm/RegionSelector.jsx
  tdrs-frontend/src/components/RequestAccessForm/RequestAccessForm.jsx
Labels: frontend, backend, dev, Ready to Merge, a11y-review

#3466 [FRA] RowSchema/Field Tech Memo
  docs/Technical-Documentation/tech-memos/fra-schema-and-fields/UpdatedErrorReport.xlsx
  docs/Technical-Documentation/tech-memos/fra-schema-and-fields/fra-schema-and-fields.md
Labels: backend, dev, raft review, documentation

#3361 3205 reparse command refactor
  tdrs-backend/docker-compose.yml
  tdrs-backend/tdpservice/data_files/tasks.py
  tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py
  tdrs-backend/tdpservice/search_indexes/reparse.py
  tdrs-backend/tdpservice/search_indexes/test/test_reparse.py
  tdrs-backend/tdpservice/search_indexes/utils.py
Labels: backend, Ready to Merge

#3456 Fix File Input Collapse
  tdrs-frontend/src/components/FileUpload/FileUpload.jsx
  tdrs-frontend/src/components/FileUpload/utils.jsx
  tdrs-frontend/src/components/STTComboBox/STTComboBox.jsx
  tdrs-frontend/src/components/SubmissionHistory/ReprocessedModal.jsx
  tdrs-frontend/src/components/SubmissionHistory/helpers.jsx
Labels: bug, frontend, dev, Ready to Merge, a11y-review

#3469 Create sprint-118-summary.md
  docs/Sprint-Review/sprint-118-summary.md
Labels: Ready to Merge

#3496 Create sprint-119-summary.md
  docs/Sprint-Review/sprint-119-summary.md
Labels: Ready to Merge

#3445 3398 - FRA Reports - search and upload
  tdrs-backend/tdpservice/conftest.py
  tdrs-backend/tdpservice/data_files/migrations/0018_alter_datafile_section.py
  tdrs-backend/tdpservice/data_files/models.py
  tdrs-backend/tdpservice/data_files/serializers.py
  tdrs-backend/tdpservice/data_files/test/test_api.py
  tdrs-backend/tdpservice/data_files/test/test_models.py
  tdrs-backend/tdpservice/data_files/test/test_serializers.py
  tdrs-backend/tdpservice/data_files/validators.py
  tdrs-backend/tdpservice/users/migrations/0044_alter_user_feature_flags.py
  tdrs-backend/tdpservice/users/models.py
  tdrs-backend/tdpservice/users/serializers.py
  tdrs-backend/tdpservice/users/test/test_models.py
  tdrs-frontend/src/actions/fraReports.js
  tdrs-frontend/src/actions/fraReports.test.js
  tdrs-frontend/src/actions/reports.js
  tdrs-frontend/src/actions/reports.test.js
  tdrs-frontend/src/components/ComboBox/index.js
  tdrs-frontend/src/components/FileUpload/FileUpload.jsx
  tdrs-frontend/src/components/FileUpload/utils.jsx
  tdrs-frontend/src/components/Form/ComboBox.jsx
  tdrs-frontend/src/components/Form/ComboBox.test.js
  tdrs-frontend/src/components/Form/DropdownSelect.jsx
  tdrs-frontend/src/components/Form/RadioSelect.jsx
  tdrs-frontend/src/components/Form/index.js
  tdrs-frontend/src/components/Header/Header.jsx
  tdrs-frontend/src/components/Header/Header.test.js
  tdrs-frontend/src/components/PermissionGuard/PermissionGuard.jsx
  tdrs-frontend/src/components/PermissionGuard/PermissionGuard.test.js
  tdrs-frontend/src/components/PrivateRoute/PrivateRoute.js
  tdrs-frontend/src/components/Reports/FRAReports.jsx
  tdrs-frontend/src/components/Reports/FRAReports.test.js
  tdrs-frontend/src/components/Reports/Reports.jsx
  tdrs-frontend/src/components/Reports/index.js
  tdrs-frontend/src/components/Reports/utils.js
  tdrs-frontend/src/components/Routes/Routes.js
  tdrs-frontend/src/components/STTComboBox/STTComboBox.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.jsx
  tdrs-frontend/src/components/SiteMap/SiteMap.test.js
  tdrs-frontend/src/components/SubmissionHistory/SubmissionHistory.test.js
  tdrs-frontend/src/reducers/fraReports.js
  tdrs-frontend/src/reducers/index.js
  tdrs-frontend/src/selectors/auth.js
  tdrs-frontend/src/utils/stringUtils.js
Labels: Ready to Merge

#3492 Update about-email-notifications.html
  product-updates/knowledge-center/about-email-notifications.html
  product-updates/knowledge-center/index.html
Labels: Research & Design, Ready to Merge
